"""Keep source identity out of compilation commands for unrelated libraries."""

import json
import os
import shlex
import tempfile
from pathlib import Path


def configure_metadata_identity(env, git_sha: str, timestamp: str) -> None:
    project = Path(env.subst("$PROJECT_DIR")).resolve()
    profile = env.subst("$PIOENV")
    directory = project / ".pio/open-bike-build/build-identity" / profile
    current = project
    for part in directory.relative_to(project).parts:
        current /= part
        if current.is_symlink() or (current.exists() and not current.is_dir()):
            raise RuntimeError("unsafe firmware identity directory")
        current.mkdir(exist_ok=True)
    header = directory / "firmware_identity.h"
    identity = (
        "// Generated by the verified firmware build.\n"
        f"#define GIT_SHA {json.dumps(git_sha)}\n"
        f"#define BUILD_TIMESTAMP {json.dumps(timestamp)}\n"
    )
    clock = directory / "firmware_compile_clock.h"
    # Arduino's chip report uses these macros even with IDF compile-date
    # descriptors disabled. Make their values explicit compiler inputs rather
    # than inheriting SOURCE_DATE_EPOCH, which SCons does not fingerprint.
    clock_contents = '''// Generated compiler clock; source time lives in firmware_metadata.
#ifndef OPEN_BIKE_FIRMWARE_COMPILE_CLOCK_H
#define OPEN_BIKE_FIRMWARE_COMPILE_CLOCK_H
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wbuiltin-macro-redefined"
#undef __DATE__
#undef __TIME__
#undef __TIMESTAMP__
#define __DATE__ "Jan  1 1970"
#define __TIME__ "00:00:00"
#define __TIMESTAMP__ "Thu Jan  1 00:00:00 1970"
#pragma GCC diagnostic pop
#endif
'''
    for generated, contents in ((header, identity), (clock, clock_contents)):
        if generated.is_symlink() or (generated.exists() and (not generated.is_file() or generated.stat().st_nlink != 1)):
            raise RuntimeError("unsafe firmware identity header")
        if not generated.exists() or generated.read_text() != contents:
            with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=directory, delete=False) as stream:
                stream.write(contents)
                temporary = Path(stream.name)
            try:
                os.replace(temporary, generated)
            finally:
                temporary.unlink(missing_ok=True)

    env.Append(CCFLAGS=[
        "-Werror=date-time",
        "-include", str(clock),
        f"-ffile-prefix-map={project}=/open-bike-computer/esp32",
    ])

    def metadata_object(build_env, node):
        source = Path(node.srcnode().get_abspath())
        if source != project / "lib/firmware_metadata/firmware_metadata.cpp":
            result = build_env.Object(node)
            build_env.Depends(result, str(clock))
            return result
        identity_env = build_env.Clone()
        identity_env.Append(CCFLAGS=["-include", str(header)])
        result = identity_env.Object(node)
        identity_env.Depends(result, str(clock))
        identity_env.Depends(result, str(header))
        return result

    env.AddBuildMiddleware(metadata_object)


def relocate_core_text(root: Path, source_project: Path, project: Path) -> int:
    """Rebase UTF-8 launchers/configuration; compiled binary inputs stay exact.

    Archive extraction already rebases absolute symlinks. The caller verifies
    the complete transport archive before extraction and attests the derived
    local tree before executing anything from it.
    """
    old = os.fsencode(str(source_project))
    new = os.fsencode(str(project))
    old_uri = source_project.as_uri().encode("utf-8")
    new_uri = project.as_uri().encode("utf-8")

    def rebase(contents):
        # PlatformIO package metadata stores percent-encoded file:// URLs.
        return contents.replace(old_uri, new_uri).replace(old, new)
    changed = 0
    for directory, _, files in os.walk(root, followlinks=False):
        for name in files:
            path = Path(directory) / name
            if path.is_symlink():
                continue
            data = path.read_bytes()
            if (old not in data and old_uri not in data) or b"\x00" in data:
                continue
            try:
                data.decode("utf-8")
            except UnicodeDecodeError:
                continue
            relocated = rebase(data)
            if data.startswith(b"#!" + old):
                # A launcher created in a path without spaces may be restored
                # into a path with spaces. The kernel cannot parse that Python
                # shebang; use the standard shell/Python exec trampoline.
                first, _, body = data.partition(b"\n")
                command = shlex.split(first[2:].decode("utf-8"))
                if command and "python" in Path(command[0]).name:
                    command = [argument.replace(str(source_project), str(project)) for argument in command]
                    quoted = " ".join(shlex.quote(argument) for argument in command)
                    relocated = (
                        "#!/bin/sh\n'''exec' " + quoted + ' "$0" "$@"\n' + "' '''\n"
                    ).encode("utf-8") + rebase(body)
            elif data.startswith(b"#!/bin/sh\n'''exec' "):
                lines = data.split(b"\n", 3)
                if len(lines) == 4 and lines[2] == b"' '''":
                    arguments = shlex.split(lines[1].decode("utf-8"))
                    if arguments[0] == "exec" and arguments[-2:] == ["$0", "$@"]:
                        command = [argument.replace(str(source_project), str(project)) for argument in arguments[1:-2]]
                        quoted = " ".join(shlex.quote(argument) for argument in command)
                        relocated = (
                            "#!/bin/sh\n'''exec' " + quoted + ' "$0" "$@"\n' + "' '''\n"
                        ).encode("utf-8") + rebase(lines[3])
            path.write_bytes(relocated)
            changed += 1
    return changed
