#!/usr/bin/env python3
"""Reproduce the offline Natural Earth texture. Requires Pillow==11.3.0."""

from __future__ import annotations

import argparse
import hashlib
import io
import json
from pathlib import Path
import sys
import zipfile

import PIL
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tools/world-radio-map/natural-earth.png"
OUTPUT = ROOT / "lib/world_radio/world_radio_map_data.inc"
MANIFEST = ROOT / "tools/world-radio-map/manifest.json"
SOURCE_URL = "https://naturalearth.s3.amazonaws.com/10m_raster/NE1_LR_LC_SR_W.zip"
ARCHIVE_SHA256 = "8e30c15d49bc73223a36eaeffc07fd49998e658e373a5498f276f5d26bfd1d0a"
SOURCE_SHA256 = "b6dcca3dd9fe06d171dea1c3b407575c610cb43995449ca4a13c32b2e315bbc4"
WIDTH, HEIGHT = 1024, 512


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def import_archive(path: Path) -> None:
    if PIL.__version__ != "11.3.0":
        raise ValueError("Use Pillow==11.3.0 for deterministic import")
    data = path.read_bytes()
    if digest(data) != ARCHIVE_SHA256:
        raise ValueError("Natural Earth archive checksum mismatch")
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        # The pinned source is WGS84 plate carree: -180..180, 90..-90.
        transform = tuple(float(v) for v in archive.read("NE1_LR_LC_SR_W.tfw").split())
        expected = (1 / 45, 0, 0, -1 / 45, -180 + 1 / 90, 90 - 1 / 90)
        if any(abs(a - b) > 1e-10 for a, b in zip(transform, expected)) or len(transform) != 6:
            raise ValueError("Unexpected map georeferencing")
        # Permit only the known 16200x8100 source, after archive verification.
        Image.MAX_IMAGE_PIXELS = 16200 * 8100
        with archive.open("NE1_LR_LC_SR_W.tif") as stream:
            original = Image.open(stream)
            if original.size != (16200, 8100):
                raise ValueError("Unexpected Natural Earth dimensions")
            reduced = original.convert("RGB").resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)
    SOURCE.parent.mkdir(parents=True, exist_ok=True)
    reduced.save(SOURCE, format="PNG", optimize=False, compress_level=9)
    print(f"Imported source PNG SHA-256: {digest(SOURCE.read_bytes())}")


def pack(indices: bytes) -> bytes:
    """Packets: bit 7 means repeat; low 7 bits + 1 give pixel count."""
    result = bytearray()
    position = 0

    def run_length(start: int) -> int:
        length = 1
        while start + length < len(indices) and length < 128 and indices[start + length] == indices[start]:
            length += 1
        return length

    while position < len(indices):
        run = run_length(position)
        if run >= 3:
            result.extend((0x80 | (run - 1), indices[position]))
            position += run
        else:
            start = position
            position += run
            while position < len(indices) and position - start < 128:
                run = run_length(position)
                if run >= 3:
                    break
                position += min(run, 128 - (position - start))
            result.append(position - start - 1)
            result.extend(indices[start:position])
    return bytes(result)


def generate() -> tuple[bytes, bytes, Image.Image]:
    if PIL.__version__ != "11.3.0":
        raise ValueError("Use Pillow==11.3.0 for deterministic generation")
    source = SOURCE.read_bytes()
    if digest(source) != SOURCE_SHA256:
        raise ValueError("Pinned source PNG checksum mismatch")
    image = Image.open(io.BytesIO(source)).convert("RGB")
    if image.size != (WIDTH, HEIGHT):
        raise ValueError("Unexpected source PNG dimensions")
    indexed = image.quantize(colors=256, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    palette = indexed.getpalette()
    colors = [((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
              for r, g, b in zip(palette[0::3], palette[1::3], palette[2::3])]
    colors += [0] * (256 - len(colors))
    packed = pack(indexed.tobytes())
    decoded = b"".join(colors[index].to_bytes(2, "little") for index in indexed.tobytes())
    fingerprint = 2166136261
    for byte in decoded:
        fingerprint = ((fingerprint ^ byte) * 16777619) & 0xffffffff
    rows = ["  " + ", ".join(f"0x{v:04x}" for v in colors[i:i + 8]) + ","
            for i in range(0, 256, 8)]
    code = "// Generated by tools/generate_world_radio_map.py; do not edit.\n"
    code += "// Made with Natural Earth (public domain); see tools/world-radio-map/README.md.\n"
    code += "static constexpr uint16_t kMapPalette[256] = {\n" + "\n".join(rows) + "\n};\n"
    code += "static constexpr uint8_t kMapPackets[] = {\n"
    code += "\n".join("  " + ", ".join(f"0x{v:02x}" for v in packed[i:i + 16]) + ","
                      for i in range(0, len(packed), 16)) + "\n};\n"
    metadata = {
        "schema": 1, "sourceUrl": SOURCE_URL, "sourceArchiveSha256": ARCHIVE_SHA256,
        "sourceArchiveVersion": "2.0.0", "sourcePngSha256": digest(source),
        "license": "public domain", "licenseUrl": "https://www.naturalearthdata.com/about/terms-of-use/",
        "projection": "WGS84 plate carree; west=-180 east=180 north=90 south=-90",
        "width": WIDTH, "height": HEIGHT, "paletteEntries": 256,
        "packetBytes": len(packed), "flashDataBytes": len(packed) + 512,
        "decodedBytes": WIDTH * HEIGHT * 2, "pillowVersion": PIL.__version__,
        "generatedSourceSha256": digest(code.encode()),
        "decodedRgb565Sha256": digest(decoded), "decodedFnv1a32": f"{fingerprint:08x}",
    }
    # Exact RGB565 palette preview, not a mock-up or a device screenshot.
    preview = indexed.copy()
    preview.putpalette([channel for v in colors for channel in
                        (((v >> 11) * 255 // 31), (((v >> 5) & 63) * 255 // 63), ((v & 31) * 255 // 31))])
    return code.encode(), (json.dumps(metadata, indent=2, sort_keys=True) + "\n").encode(), preview.convert("RGB")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--import-archive", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()
    if args.import_archive:
        if args.check:
            parser.error("--import-archive and --check are mutually exclusive")
        import_archive(args.import_archive)
        return 0
    code, metadata, preview = generate()
    for path, expected in ((OUTPUT, code), (MANIFEST, metadata)):
        if args.check:
            if not path.is_file() or path.read_bytes() != expected:
                print(f"Generated map drift: {path}", file=sys.stderr)
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)
    if args.preview:
        preview.save(args.preview)
    print(metadata.decode(), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
