// Generated by tools/generate_ride_ble_contract.py. Do not edit.
nonisolated enum RideAutomationSourceHealth {
    static let wheelFresh: UInt16 = 1 << 0
    static let cadenceFresh: UInt16 = 1 << 1
    static let gpsFresh: UInt16 = 1 << 2
    static let imuFresh: UInt16 = 1 << 3
    static let watchGpsFresh: UInt16 = 1 << 4
    static let mask: UInt16 = 31
}
