// Generated by tools/generate_ride_ble_contract.py. Do not edit.
nonisolated enum WorkoutZoneWireV1 {
    static let version = 1
    static let frameKind = 5
    static let headerBytes = 32
    static let maximumZones = 9
    static let minimumZones = 3
    static let maximumFrameBytes = 132
    static let heartRateMaximumAgeMs = 30000
    static let powerMaximumAgeMs = 5000
    static let streamMaximumAgeMs = 10000
    static let flagFinal = 1
    static let flagLowerBoundZero = 2
    static let flagDurations = 4
    static let metricHeartRate = 1
    static let metricCyclingPower = 2
    static let sourceBicino = 0
    static let sourceHealthkitSystem = 1
    static let sourceHealthkitUser = 2
    static let sourceHealthkitApp = 3
    static let sourceHealthkitUnknown = 4
    static let offsetKind = 0
    static let offsetVersion = 1
    static let offsetMetric = 2
    static let offsetSource = 3
    static let offsetFlags = 4
    static let offsetCount = 5
    static let offsetCurrentZone = 6
    static let offsetState = 7
    static let offsetSessionToken = 8
    static let offsetSampleAgeMs = 10
    static let offsetSequence = 12
    static let offsetSessionUuid = 16
    static let offsetBoundaries = 32
}
