#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec


REPO_ROOT = Path(__file__).resolve().parents[3]
BACKEND_ROOT = REPO_ROOT / "map-platform" / "backend"
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from map_platform.map_stream_trust_registry import (  # noqa: E402
    FORBIDDEN_FIXTURE_KEY_IDS,
    FORBIDDEN_FIXTURE_PUBLIC_KEYS,
    KEY_ID_PATTERN,
    TrustKey,
    load_trust_registry,
    parse_trust_date,
)


REGISTRY_PATH = REPO_ROOT / "map-platform" / "config" / "map-stream-trust.json"
SWIFT_PATH = (
    REPO_ROOT
    / "ios-app"
    / "BikeComputer"
    / "BikeComputer"
    / "Models"
    / "BikeMapStreamProductionTrust.generated.swift"
)
CPP_PATH = (
    REPO_ROOT
    / "esp32"
    / "lib"
    / "map_transfer"
    / "map_stream_compiled_keys.generated.inc"
)


def load_registry(path: Path = REGISTRY_PATH) -> list[TrustKey]:
    return load_trust_registry(path)


def render_swift(keys: list[TrustKey]) -> str:
    trusted = [key for key in keys if key.state == "trusted"]
    lines = [
        "// Generated by map-platform/backend/tools/generate_map_stream_trust.py.",
        "// Public verification keys only. Never place private material here.",
        "import Foundation",
        "",
        "extension BikeMapStreamTrustStore {",
    ]
    if not trusted:
        lines.extend(
            [
                "    nonisolated static let production = BikeMapStreamTrustStore(publicKeysByID: [:])",
                "}",
                "",
            ]
        )
        return "\n".join(lines)
    lines.append(
        "    nonisolated static let production = BikeMapStreamTrustStore(publicKeysByID: ["
    )
    for key in trusted:
        lines.extend(
            [
                f'        "{key.key_id}": Data(mapStreamHexLiteral: "{key.public_key_x963_hex}"),',
            ]
        )
    lines.extend(["    ])", "}", ""])
    return "\n".join(lines)


def render_cpp(keys: list[TrustKey]) -> str:
    trusted = [key for key in keys if key.state == "trusted"]
    lines = [
        "// Generated by map-platform/backend/tools/generate_map_stream_trust.py.",
        "// Public verification keys only. Never place private material here.",
    ]
    if not trusted:
        lines.append("constexpr std::array<CompiledKey, 0> kCompiledKeys = {};")
    else:
        lines.append(
            f"constexpr std::array<CompiledKey, {len(trusted)}> kCompiledKeys = {{{{"
        )
        for key in trusted:
            fingerprint = hashlib.sha256(
                bytes.fromhex(key.public_key_x963_hex)
            ).hexdigest()
            lines.append(
                f'    {{"{key.key_id}", "{key.public_key_x963_hex}", "{fingerprint}"}},'
            )
        lines.append("}};")
    lines.append("")
    return "\n".join(lines)


def expected_outputs(path: Path = REGISTRY_PATH) -> dict[Path, str]:
    keys = load_registry(path)
    return {
        SWIFT_PATH: render_swift(keys),
        CPP_PATH: render_cpp(keys),
    }


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_outputs(outputs: dict[Path, str]) -> bool:
    stale = []
    for path, expected in outputs.items():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            actual = None
        if actual != expected:
            stale.append(path.relative_to(REPO_ROOT))
    if stale:
        print(
            "generated map stream trust files are stale: "
            + ", ".join(str(path) for path in stale),
            file=sys.stderr,
        )
        return False
    return True


def public_registry_entry_from_private_key(
    private_key_path: Path,
    *,
    key_id: str,
    created_at: str,
    retire_after: str | None,
) -> dict[str, str]:
    if not KEY_ID_PATTERN.fullmatch(key_id) or key_id in FORBIDDEN_FIXTURE_KEY_IDS:
        raise ValueError("production signing key ID is invalid or reserved")
    created_at = parse_trust_date(created_at, "createdAt")
    if retire_after is not None:
        retire_after = parse_trust_date(retire_after, "retireAfter")
        if retire_after <= created_at:
            raise ValueError("trust-key retirement must be after creation")
    try:
        key_stat = private_key_path.stat()
    except OSError as exc:
        raise ValueError(f"map signing private key is unreadable: {exc}") from exc
    if (
        private_key_path.is_symlink()
        or not private_key_path.is_file()
        or key_stat.st_mode & 0o077
    ):
        raise ValueError(
            "map signing private key must be a regular file readable only by its owner"
        )
    try:
        private_key = serialization.load_pem_private_key(
            private_key_path.read_bytes(),
            password=None,
        )
    except (OSError, TypeError, ValueError) as exc:
        raise ValueError(f"map signing private key is unreadable: {exc}") from exc
    if not isinstance(private_key, ec.EllipticCurvePrivateKey) or not isinstance(
        private_key.curve,
        ec.SECP256R1,
    ):
        raise ValueError("map signing private key must use P-256")
    public_key = private_key.public_key().public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint,
    ).hex()
    if public_key in FORBIDDEN_FIXTURE_PUBLIC_KEYS:
        raise ValueError("golden-vector private keys are forbidden for production")
    result = {
        "keyId": key_id,
        "publicKeyX963Hex": public_key,
        "state": "trusted",
        "createdAt": created_at,
    }
    if retire_after is not None:
        result["retireAfter"] = retire_after
    return result


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate and render the map-stream public trust registry."
    )
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--check", action="store_true")
    action.add_argument("--write", action="store_true")
    action.add_argument("--inspect-private-key", type=Path)
    parser.add_argument("--key-id")
    parser.add_argument("--created-at")
    parser.add_argument("--retire-after")
    args = parser.parse_args()
    try:
        if args.inspect_private_key:
            if not args.key_id or not args.created_at:
                raise ValueError(
                    "--key-id and --created-at are required with --inspect-private-key"
                )
            print(
                json.dumps(
                    public_registry_entry_from_private_key(
                        args.inspect_private_key,
                        key_id=args.key_id,
                        created_at=args.created_at,
                        retire_after=args.retire_after,
                    ),
                    indent=2,
                )
            )
            return 0
        if args.key_id or args.created_at or args.retire_after:
            raise ValueError(
                "key metadata is only valid with --inspect-private-key"
            )
        outputs = expected_outputs()
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    if args.check:
        return 0 if check_outputs(outputs) else 1
    write_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
