#pragma once

#ifndef DEVICE_REMOTE_DEBUG
#define DEVICE_REMOTE_DEBUG 0
#endif

namespace device_debug {

#if DEVICE_REMOTE_DEBUG
inline constexpr char kBrowserPage[] = R"HTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Bicino device debug</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#111;color:#eee}body{margin:0;padding:24px;display:grid;gap:16px;justify-items:center}header,.panel{width:min(94vw,720px)}h1{font-size:1.25rem;margin:0 0 8px}.status{color:#9ad}.error{color:#ff8e8e}canvas{display:block;width:min(90vw,620px);height:auto;touch-action:none;background:#000;border:1px solid #444;border-radius:10px}.screen{position:relative}.overlay{position:absolute;inset:0;display:none;place-items:center;background:#0009;font-size:1.4rem;border-radius:10px}.actions{display:flex;gap:8px;flex-wrap:wrap}button{padding:9px 13px;border:1px solid #555;border-radius:8px;background:#252525;color:#fff;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#181818;padding:12px;border-radius:8px}.truth{font-size:.85rem;color:#bbb}
</style></head><body><header><h1>Bicino real-device debugger</h1><div id="status" class="status">Connecting…</div></header>
<main class="panel"><p class="truth"><strong>Synthetic pointer:</strong> click or drag the framebuffer to inject LVGL input.</p><div class="screen"><canvas id="screen"></canvas><div id="overlay" class="overlay"></div></div>
<div class="actions"><button id="reconnect">Reconnect</button><button id="boot">BOOT (short press)</button><button id="wake">Wake display</button><button id="png">Save PNG</button><button id="exit">End session</button></div>
<pre id="info">No device information yet.</pre><p class="truth">This is the framebuffer the firmware intended to show, with synthetic pointer input. It does not prove that the physical AMOLED pixels or touch controller are working.</p></main>
<script>
(()=>{'use strict';
let token='';try{token=decodeURIComponent(location.hash.slice(1))}catch{}history.replaceState(null,'',location.pathname);
const $=id=>document.getElementById(id),canvas=$('screen'),ctx=canvas.getContext('2d',{alpha:false}),status=$('status'),infoBox=$('info'),overlay=$('overlay');
let running=false,failures=0,sequence=0,displayedSequence=0,displayedCapturedAtMs=0,identity='',target='device',shortGitSha='unknown',deviceClockOffsetMs=0,lastRequestLatencyMs=0,eventSequence=0,eventSequenceInitialized=false,pointerDown=false,lastPointer={x:0,y:0},lastMoveAt=0,pollTimer=0,heartbeat=0,polling=false,pollRequested=false,lastInfoAt=0,drawFrame=null,drawHandle=0,pointerChain=Promise.resolve(),moveInFlight=false,pendingMove=null,frameAbortController=null,pointerInteractionActive=false,frameWidth=0,frameHeight=0,viewRotation=0;
const auth=()=>({'X-BikeComputer-Transfer-Token':token});
function message(text,error=false){status.textContent=text;status.className=error?'error':'status'}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
async function timedFetch(path,options={},controller=new AbortController()){const timer=setTimeout(()=>controller.abort(),8000);try{return await fetch(path,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
async function json(path,options={}){const response=await timedFetch(path,{...options,headers:{...auth(),...(options.headers||{})},cache:'no-store'});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.code||`HTTP ${response.status}`);return body}
function setDisplayState(state){if(state==='active'){overlay.style.display='none'}else{overlay.textContent=state==='off'?'Display off':'Display dimmed';overlay.style.display='grid'}}
const displayPoint=(x,y,w,h,r)=>r===1?[y,w-1-x]:r===2?[w-1-x,h-1-y]:r===3?[h-1-y,x]:[x,y];
const panelPoint=(x,y,w,h,r)=>r===1?[w-1-y,x]:r===2?[w-1-x,h-1-y]:r===3?[y,h-1-x]:[x,y];
async function loadInfo(syncPointerSequence=false){const started=performance.now(),data=await json('/device-debug/v1/info'),finished=performance.now(),dimensions={WAVESHARE_AMOLED_175:'466x466',WAVESHARE_AMOLED_206:'410x502'},rotations={WAVESHARE_AMOLED_175:1,WAVESHARE_AMOLED_206:0},firmware=data.firmware||{},size=`${data.width}x${data.height}`,pointerLastSequence=data.counters?.pointerLastSequence,pointerSequenceInitialized=data.counters?.pointerSequenceInitialized;if(data.ok!==true||data.schema!==1||data.session?.active!==true||data.session?.mode!=='debug'||data.pixelFormat!=='rgb565le'||dimensions[data.target]!==size||data.viewRotation!==rotations[data.target]||!RegExp('^[0-9a-f]{16}$').test(data.deviceId)||firmware.target!==data.target||typeof firmware.version!=='string'||!firmware.version||!Number.isInteger(firmware.build)||!RegExp('^[0-9a-f]{40}$').test(firmware.gitSha)||data.buildProfile!==`${data.target}_REMOTE_DEBUG`||!Number.isInteger(data.uptimeMs)||!Number.isInteger(pointerLastSequence)||pointerLastSequence<0||pointerLastSequence>0xffffffff||typeof pointerSequenceInitialized!=='boolean')throw new Error('Unsupported or incomplete device identity');const nextIdentity=`${data.target}/${data.deviceId}/${size}/${data.viewRotation}/${data.buildProfile}/${firmware.gitSha}`;if(identity&&identity!==nextIdentity){running=false;throw new Error('Connected device identity changed')}identity=nextIdentity;if(!eventSequenceInitialized||syncPointerSequence){eventSequence=pointerSequenceInitialized?pointerLastSequence:0;eventSequenceInitialized=true}target=data.target;shortGitSha=firmware.gitSha.slice(0,8);deviceClockOffsetMs=data.uptimeMs-finished;lastRequestLatencyMs=Math.round(finished-started);frameWidth=data.width;frameHeight=data.height;viewRotation=data.viewRotation;const displayWidth=viewRotation%2?frameHeight:frameWidth,displayHeight=viewRotation%2?frameWidth:frameHeight;if(canvas.width!==displayWidth||canvas.height!==displayHeight){canvas.width=displayWidth;canvas.height=displayHeight}setDisplayState(data.displayState);infoBox.textContent=JSON.stringify(data,null,2);lastInfoAt=finished;return data}
function parseFrame(buffer){if(buffer.byteLength<32)throw new Error('Short frame');const v=new DataView(buffer),u=new Uint8Array(buffer);if(String.fromCharCode(...u.slice(0,4))!=='BCF1')throw new Error('Bad frame magic');const header=v.getUint16(4,true),flags=v.getUint16(6,true),width=v.getUint16(16,true),height=v.getUint16(18,true),stride=v.getUint16(20,true),format=v.getUint8(22),orientation=v.getUint8(23),payloadBytes=v.getUint32(24,true),expectedCrc=v.getUint32(28,true);if(header<32||flags!==0||format!==1||orientation!==0||width!==frameWidth||height!==frameHeight||stride<width*2||payloadBytes!==stride*height||buffer.byteLength!==header+payloadBytes)throw new Error('Invalid frame metadata');const payload=u.subarray(header);if(crc32(payload)!==expectedCrc)throw new Error('Frame CRC mismatch');return{seq:v.getUint32(8,true),capturedAtMs:v.getUint32(12,true),width,height,stride,payload}}
function draw(frame){const image=ctx.createImageData(canvas.width,canvas.height),out=image.data,p=frame.payload;for(let y=0;y<frame.height;y++)for(let x=0;x<frame.width;x++){const i=y*frame.stride+x*2,value=p[i]|(p[i+1]<<8),[dx,dy]=displayPoint(x,y,frame.width,frame.height,viewRotation),o=(dy*canvas.width+dx)*4;out[o]=((value>>11)&31)*255/31;out[o+1]=((value>>5)&63)*255/63;out[o+2]=(value&31)*255/31;out[o+3]=255}ctx.putImageData(image,0,0)}
function frameAge(capturedAtMs){return (((performance.now()+deviceClockOffsetMs)>>>0)-capturedAtMs)>>>0}
function scheduleDraw(frame){drawFrame=frame;if(drawHandle)return;drawHandle=requestAnimationFrame(()=>{drawHandle=0;const next=drawFrame;drawFrame=null;if(next){draw(next);displayedSequence=next.seq;displayedCapturedAtMs=next.capturedAtMs;$('png').disabled=false;message(`Live · frame ${displayedSequence} · age ${frameAge(displayedCapturedAtMs)} ms · request ${lastRequestLatencyMs} ms`)}})}
function requestPoll(){if(!running||pointerInteractionActive)return;pollRequested=true;if(!polling){clearTimeout(pollTimer);pollTimer=setTimeout(poll,0)}}
async function poll(){if(!running||polling||pointerInteractionActive)return;polling=true;pollRequested=false;let frameController=null;try{if(performance.now()-lastInfoAt>2500)await loadInfo();frameController=new AbortController();frameAbortController=frameController;const started=performance.now(),response=await timedFetch(`/device-debug/v1/frame?after=${sequence}`,{headers:auth(),cache:'no-store'},frameController);if(response.status===204){lastRequestLatencyMs=Math.round(performance.now()-started);failures=0;message(displayedSequence?`Connected · frame ${displayedSequence} · age ${frameAge(displayedCapturedAtMs)} ms · request ${lastRequestLatencyMs} ms`:'Connected · waiting for first frame')}else if(response.ok){const frame=parseFrame(await response.arrayBuffer());lastRequestLatencyMs=Math.round(performance.now()-started);sequence=frame.seq;scheduleDraw(frame);failures=0}else throw new Error(`Frame HTTP ${response.status}`)}catch(error){if(!(pointerInteractionActive&&error.name==='AbortError')){failures++;message(`Stale · retry ${failures}/5 · ${error.message}`,true);if(failures>=5){running=false;message(`Stopped: ${error.message}`,true)}}}finally{if(frameAbortController===frameController)frameAbortController=null;polling=false;if(running&&!pointerInteractionActive)pollTimer=setTimeout(poll,pollRequested?0:(failures?750:200))}}
async function connect(){clearTimeout(pollTimer);if(frameAbortController)frameAbortController.abort();frameAbortController=null;pointerInteractionActive=false;if(drawHandle)cancelAnimationFrame(drawHandle);drawHandle=0;drawFrame=null;running=false;failures=0;pollRequested=false;$('png').disabled=true;if(!token){message('Missing session token in URL fragment',true);return}try{await loadInfo();running=true;message('Connected');requestPoll()}catch(error){message(`Connection failed: ${error.message}`,true)}}
function point(event){const r=canvas.getBoundingClientRect(),dx=Math.max(0,Math.min(canvas.width-1,Math.floor((event.clientX-r.left)*canvas.width/r.width))),dy=Math.max(0,Math.min(canvas.height-1,Math.floor((event.clientY-r.top)*canvas.height/r.height))),[x,y]=panelPoint(dx,dy,frameWidth,frameHeight,viewRotation);return{x,y}}
function beginPointerInteraction(){pointerInteractionActive=true;clearTimeout(pollTimer);pollRequested=false;if(frameAbortController)frameAbortController.abort()}
async function finishPointerInteraction(){await pointerChain;if(pointerDown||!pointerInteractionActive)return;pointerInteractionActive=false;requestPoll()}
async function sendPointerNow(phase,p,retrySequence=true){lastPointer=p;const body={schema:1,eventSequence:(++eventSequence)>>>0,pointerId:0,phase,x:p.x,y:p.y};const response=await timedFetch('/device-debug/v1/pointer',{method:'POST',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});if(!response.ok){const data=await response.json().catch(()=>null),code=data?.error?.code;if(retrySequence&&code==='pointer_sequence'){await loadInfo(true);return sendPointerNow(phase,p,false)}throw new Error(code||`Pointer HTTP ${response.status}`)}requestPoll()}
function enqueuePointer(phase,p){const operation=pointerChain.then(()=>sendPointerNow(phase,p));pointerChain=operation.catch(()=>{});operation.catch(error=>{message(error.message,true);pointerDown=false;pendingMove=null;if(phase!=='cancel'){const cancel=pointerChain.then(()=>sendPointerNow('cancel',p));pointerChain=cancel.catch(()=>{})}finishPointerInteraction().catch(()=>{})});return operation}
function queueMove(p){pendingMove=p;if(moveInFlight||!pointerDown)return;moveInFlight=true;const next=pendingMove;pendingMove=null;enqueuePointer('move',next).finally(()=>{moveInFlight=false;if(pendingMove&&pointerDown)queueMove(pendingMove)}).catch(()=>{})}
function cancelActivePointer(){if(!pointerDown)return;pointerDown=false;pendingMove=null;enqueuePointer('cancel',lastPointer).finally(finishPointerInteraction).catch(()=>{})}
canvas.addEventListener('pointerdown',event=>{if(!running||pointerDown)return;beginPointerInteraction();pointerDown=true;lastMoveAt=performance.now();canvas.setPointerCapture(event.pointerId);const p=point(event);lastPointer=p;enqueuePointer('down',p)});
canvas.addEventListener('pointermove',event=>{if(!pointerDown)return;const now=performance.now(),p=point(event);lastPointer=p;if(now-lastMoveAt<40){pendingMove=p;return}lastMoveAt=now;queueMove(p)});
function release(event,phase='up'){if(!pointerDown)return;const p=point(event);pointerDown=false;pendingMove=null;enqueuePointer(phase,p).finally(finishPointerInteraction).catch(()=>{})}
canvas.addEventListener('pointerup',event=>release(event));canvas.addEventListener('pointercancel',event=>release(event,'cancel'));canvas.addEventListener('lostpointercapture',event=>release(event,'cancel'));
heartbeat=setInterval(()=>{if(pointerDown)queueMove(lastPointer)},500);addEventListener('blur',cancelActivePointer);addEventListener('keydown',event=>{if(event.key==='Escape')cancelActivePointer()});document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelActivePointer()});
$('reconnect').onclick=connect;$('boot').onclick=async()=>{try{await json('/device-debug/v1/button/boot',{method:'POST'});message('BOOT short press requested');requestPoll()}catch(error){message(error.message,true)}};$('wake').onclick=async()=>{try{await json('/device-debug/v1/display/wake',{method:'POST'});message('Wake requested')}catch(error){message(error.message,true)}};
$('png').onclick=()=>canvas.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bicino-${target.toLowerCase().replace(/[^a-z0-9_-]/g,'-')}-${shortGitSha}-frame-${displayedSequence}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png');
$('exit').onclick=async()=>{try{cancelActivePointer();await pointerChain;await json('/device-debug/v1/session/exit',{method:'POST'});running=false;clearTimeout(pollTimer);if(drawHandle)cancelAnimationFrame(drawHandle);drawHandle=0;drawFrame=null;$('png').disabled=true;message('Session ended')}catch(error){message(error.message,true)}};
addEventListener('beforeunload',()=>{clearInterval(heartbeat);clearTimeout(pollTimer);if(frameAbortController)frameAbortController.abort();if(drawHandle)cancelAnimationFrame(drawHandle)});connect();
})();
</script></body></html>)HTML";
#endif

} // namespace device_debug
