// Generated by tools/generate_diagnostics_contract.py. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>
#include <cstring>
namespace ride_diagnostics::registry {
inline constexpr const char *kSha256 = "bc23cad2d8decb5872331712e4368484415b8eb33485a180f6ee7500d0a789f6";
inline constexpr unsigned kSchema = 2;
inline constexpr uint32_t kInstrumentedMask = 5814230U;
inline constexpr const char *kDomains[] = {
    "audio", "ble", "boot", "display",
    "gps", "http", "lifecycle", "logger",
    "map", "memory", "navigation", "ota",
    "power", "rideAutomation", "sensor", "storage",
    "tasks", "tls", "touch", "transfer",
    "user", "wifi", "workout",
};
inline uint32_t domainMask(const char *name) {
  if (name == nullptr) return 0;
  for (std::size_t i=0; i<sizeof(kDomains)/sizeof(kDomains[0]); ++i)
    if (std::strcmp(name, kDomains[i]) == 0) return uint32_t(1) << i;
  return 0;
}
}
