// Generated by tools/generate_diagnostics_contract.py; do not edit.
#pragma once
#include <cstddef>
#include <cstdint>
namespace bicino_diagnostics::contract {
constexpr const char *kSha256 = "e951836bfa74e261701b00bc27abb956b0c5f8f92025691a481121b527f93acb";
constexpr const char *kDomains[] = {
    "audio", "ble", "boot", "capture",
    "display", "gps", "http", "lifecycle",
    "logger", "map", "memory", "native",
    "navigation", "power", "renderer", "rideAutomation",
    "storage", "task", "tls", "touch",
    "transfer", "update", "user", "watchdog",
    "wifi", "workout",
};
constexpr std::size_t kDomainCount = sizeof(kDomains) / sizeof(kDomains[0]);
constexpr const char *kLevels[] = {
    "trace", "debug", "info", "warning",
    "error", "fault",
};
constexpr uint32_t kCriticalQueue = 8U;
constexpr uint32_t kEventBytes = 768U;
constexpr uint32_t kFieldBytes = 320U;
constexpr uint32_t kMaximumCaptureSeconds = 14400U;
constexpr uint32_t kMaximumTailEvents = 32U;
constexpr uint32_t kMaximumTraceBytesPerSecond = 8192U;
constexpr uint32_t kMaximumTraceEventsPerSecond = 20U;
constexpr uint32_t kNormalQueue = 24U;
} // namespace bicino_diagnostics::contract
