// Generated by tools/generate_ride_ble_contract.py. Do not edit.
import Foundation

enum RideBLEGeneratedProtocolV1 {
    static let serviceUUID = "9D7B3F30-3F6A-4D1C-9F6D-1FBF0E8B1800"
    static let navigationUUID = "2A6E"
    static let routeUUID = "2A6F"
    static let gpsUUID = "2A72"
    static let settingsUUID = "2A73"
    static let authUUID = "9D7B3F30-3F6A-4D1C-9F6D-1FBF0E8B1002"
    static let workoutUUID = "9D7B3F30-3F6A-4D1C-9F6D-1FBF0E8B1003"
    static let rideAutomationUUID = "9D7B3F30-3F6A-4D1C-9F6D-1FBF0E8B1004"
    static let protectedFrameOverhead = 22
    static let capabilityRequestMagic = "CAPS"
    static let capabilityResponseMagic = "CAP2"
    static let capabilitySchemaVersion: UInt8 = 1
    static let currentClientVersion: UInt8 = 22
    static let deviceSoundsFeature: UInt32 = 1 << 0
    static let deviceSoundsMinimumClientVersion: UInt8 = 1
    static let powerButtonHonkFeature: UInt32 = 1 << 1
    static let powerButtonHonkMinimumClientVersion: UInt8 = 1
    static let powerButtonHonkAckFeature: UInt32 = 1 << 2
    static let powerButtonHonkAckMinimumClientVersion: UInt8 = 1
    static let independentMapProfilesFeature: UInt32 = 1 << 3
    static let independentMapProfilesMinimumClientVersion: UInt8 = 1
    static let extendedMapVisibilityFeature: UInt32 = 1 << 4
    static let extendedMapVisibilityMinimumClientVersion: UInt8 = 1
    static let batteryStatusScreenFeature: UInt32 = 1 << 5
    static let batteryStatusScreenMinimumClientVersion: UInt8 = 1
    static let destinationPickerFeature: UInt32 = 1 << 6
    static let destinationPickerMinimumClientVersion: UInt8 = 1
    static let workoutTelemetryFeature: UInt32 = 1 << 7
    static let workoutTelemetryMinimumClientVersion: UInt8 = 1
    static let streetLabelsFeature: UInt32 = 1 << 8
    static let streetLabelsMinimumClientVersion: UInt8 = 10
    static let birdsEyeMapNavigationFeature: UInt32 = 1 << 9
    static let birdsEyeMapNavigationMinimumClientVersion: UInt8 = 10
    static let birdsEyePerspectiveFeature: UInt32 = 1 << 10
    static let birdsEyePerspectiveMinimumClientVersion: UInt8 = 10
    static let birdsEyeStrongerPerspectiveFeature: UInt32 = 1 << 11
    static let birdsEyeStrongerPerspectiveMinimumClientVersion: UInt8 = 10
    static let osm3DBuildingsFeature: UInt32 = 1 << 12
    static let osm3DBuildingsMinimumClientVersion: UInt8 = 10
    static let explicitInvalidGpsHeadingFeature: UInt32 = 1 << 13
    static let explicitInvalidGpsHeadingMinimumClientVersion: UInt8 = 11
    static let scopedWatchControllerFeature: UInt32 = 1 << 14
    static let scopedWatchControllerMinimumClientVersion: UInt8 = 12
    static let rideAutomationV2Feature: UInt32 = 1 << 15
    static let rideAutomationV2MinimumClientVersion: UInt8 = 13
    static let remoteDeviceDebugFeature: UInt32 = 1 << 16
    static let remoteDeviceDebugMinimumClientVersion: UInt8 = 14
    static let gpsPositionQualityV1Feature: UInt32 = 1 << 17
    static let gpsPositionQualityV1MinimumClientVersion: UInt8 = 15
    static let rendererDiagnosticsFeature: UInt32 = 1 << 18
    static let rendererDiagnosticsMinimumClientVersion: UInt8 = 16
    static let automaticDisplayOffFeature: UInt32 = 1 << 19
    static let automaticDisplayOffMinimumClientVersion: UInt8 = 16
    static let rideDiagnosticsFeature: UInt32 = 1 << 20
    static let rideDiagnosticsMinimumClientVersion: UInt8 = 18
    static let detailedRideDiagnosticsFeature: UInt32 = 1 << 21
    static let detailedRideDiagnosticsMinimumClientVersion: UInt8 = 19
    static let rideDeliveryAckFeature: UInt32 = 1 << 22
    static let rideDeliveryAckMinimumClientVersion: UInt8 = 20
    static let rendererBenchmarkSampleFeature: UInt32 = 1 << 23
    static let rendererBenchmarkSampleMinimumClientVersion: UInt8 = 21
    static let watchGpsMotionEvidenceV1Feature: UInt32 = 1 << 24
    static let watchGpsMotionEvidenceV1MinimumClientVersion: UInt8 = 22
    static let workoutStartRequestMagic = "WREQ"
    static let destinationRequestMagic = "DREQ"
    static let applicationCommandMagic = "RCM1"
    static let applicationAcknowledgementMagic = "RAK1"
    static let applicationDeliveryVersion: UInt8 = 1
    static let applicationCommandHeaderBytes = 28
    static let applicationAcknowledgementBytes = 32
    static let maximumApplicationGroupMembers = 8
    static let completedApplicationReplayWindow = 8
    static let applicationCommandGoldenHex = "52434d310102010300112233445566778899aabbccddeeff78563412aabb"
    static let applicationAcknowledgementGoldenHex = "52414b310102000000112233445566778899aabbccddeeff7856341209000000"
}

enum RideBLEGeneratedProtectedChannelV1: UInt8, Sendable {
    case auth = 1
    case navigation = 2
    case route = 3
    case gps = 4
    case settings = 5
    case workout = 6
    case rideAutomation = 7
}

enum RideBLEGeneratedControllerRoleV1: UInt8, Sendable {
    case none = 0
    case owner = 1
    case watchRide = 2
}

enum RideBLEApplicationCommandTypeV1: UInt8, Equatable, Sendable {
    case navigationClear = 1
    case workoutState = 2
}

enum RideBLEApplicationResultV1: UInt8, Equatable, Sendable {
    case success = 0
    case stale = 1
    case busy = 2
    case unauthorized = 3
    case malformed = 4
    case resourceRejected = 5
}
