// Generated by tools/generate_diagnostics_contract.py; do not edit.
import Foundation
import CoreFoundation

nonisolated enum DiagnosticsContractV2 {
    static let sha256 = "e951836bfa74e261701b00bc27abb956b0c5f8f92025691a481121b527f93acb"
    static let domains = ["audio", "ble", "boot", "capture", "display", "gps", "http", "lifecycle", "logger", "map", "memory", "native", "navigation", "power", "renderer", "rideAutomation", "storage", "task", "tls", "touch", "transfer", "update", "user", "watchdog", "wifi", "workout"]
    static let levels = ["trace", "debug", "info", "warning", "error", "fault"]
    static let maximumCaptureSeconds: UInt32 = 14400
    static let profiles: [String: [String: String]] = [
        "baseline": [:],
        "all": ["audio": "trace", "ble": "trace", "boot": "trace", "capture": "trace", "display": "trace", "gps": "trace", "http": "trace", "lifecycle": "trace", "logger": "trace", "map": "trace", "memory": "trace", "native": "trace", "navigation": "trace", "power": "trace", "renderer": "trace", "rideAutomation": "trace", "storage": "trace", "task": "trace", "tls": "trace", "touch": "trace", "transfer": "trace", "update": "trace", "user": "trace", "watchdog": "trace", "wifi": "trace", "workout": "trace"],
        "ble-navigation": ["ble": "trace", "gps": "trace", "navigation": "trace", "rideAutomation": "trace"],
        "map-rendering": ["display": "trace", "map": "trace", "memory": "trace", "renderer": "trace", "storage": "trace"],
        "power": ["memory": "debug", "power": "debug", "task": "debug", "watchdog": "debug"],
        "transfer": ["ble": "trace", "http": "trace", "storage": "trace", "tls": "trace", "transfer": "trace", "update": "trace", "wifi": "trace"]
    ]
}

nonisolated enum RideDiagnosticsFieldPolicy {
    static let allowedKeys: Set<String> = [
        "accuracy", "accuracyAvailable", "accuracyBucket", "acknowledgedKind",
        "active", "activeStage", "ageMs", "alertMode",
        "applyErrorCode", "applyErrorDomain", "applyResult", "attempt",
        "attemptId", "authorization", "authorized", "autoPauseEnabled",
        "available", "background", "blockLoadMs", "bootSequence",
        "bytes", "bytesLimit", "bytesPerSecond", "captureState",
        "chunk", "class", "clockSynchronized", "code",
        "collectionId", "commandClass", "commandId", "compiledLevel",
        "completedStage", "connectCompleted", "connectDurationMs", "connectStarted",
        "connectionGeneration", "connectionReused", "connectionState", "consecutiveEarlyFailures",
        "controllerRole", "coredumpBytes", "coverageState", "crashAvailable",
        "cutoffSequence", "decisionSequence", "deliveryState", "diagnosticContract",
        "diagnosticHold", "discardedBytes", "domain", "droppedCount",
        "durableSequence", "durationLimit", "durationMs", "effectiveLevel",
        "emissionSequence", "enqueuedCount", "errorCode", "errorDomain",
        "eventCount", "eventsPerSecond", "expectedState", "fallback",
        "featureFlags", "filteredCount", "firmwareBuild", "firmwareFingerprint",
        "firmwareGitSha", "firmwareProfile", "firmwareTarget", "firmwareVersion",
        "firstMissingUptimeMs", "firstSequence", "fixValid", "formatVersion",
        "frameCount", "frameSkippedCount", "freeInternalBytes", "freePsramBytes",
        "generation", "grantId", "highWater", "highWaterBytes",
        "httpStatus", "importedCount", "incidentId", "incidentState",
        "kind", "largestInternalBytes", "lastCriticalCategory", "lastCriticalEvent",
        "lastFailureCompletedStage", "lastFailureResetReason", "lastFailureStage", "lastGapMs",
        "lastMissingUptimeMs", "lastSequence", "latencyMs", "leaseGeneration",
        "localAccessorySubnet", "mapDetail", "mapId", "mapPhase",
        "mapProgressMs", "markerSequence", "maxQueueDepth", "maximumGapMs",
        "members", "messageBytes", "messageDigest", "mode",
        "nativeReportCount", "navigating", "networkObservation", "networkProtocol",
        "networkTransport", "operationId", "origin", "otaState",
        "outcome", "oversizedCount", "partialBytes", "pendingControl",
        "phase", "policyDurationMs", "policyExpiresAtEpochMs", "policyGeneration",
        "profileVersion", "provider", "proxyConnection", "queueBytes",
        "queueDepth", "rateLimitedCount", "ready", "reason",
        "recorderReady", "rejectedCount", "rejectedFieldCount", "remainingChunks",
        "remoteEndpointMatched", "replacedCount", "requestedLevel", "resetReason",
        "result", "retries", "rideDetectionArmed", "rideGeneration",
        "role", "routeLoaded", "rssiBucket", "runtimeBootSequence",
        "safeMode", "sampleCount", "sampledCount", "samplingIntervalMs",
        "schemaVersion", "scope", "segmentCount", "sequence",
        "sessionPresent", "sha256Prefix", "simulation", "sizeBucket",
        "snapshotId", "sourceHealthMask", "speedAvailable", "stackHighWaterBytes",
        "startMode", "state", "stateAfter", "stateBefore",
        "storage", "storageErrorCount", "tlsChallenge", "tlsCompleted",
        "tlsDurationMs", "tlsStarted", "transition", "uiPhase",
        "uiProgressMs", "underlyingErrorCode", "underlyingErrorDomain", "viewingMap",
        "visitedEntries", "waitedForConnectivity", "watchSequence", "watchUptimeMs",
        "watchdogCoreMask", "watchdogUptimeMs", "workoutActive", "writerDelayMs",
        "writerDetail", "writerPhase", "writerProgressMs", "writtenCount",
    ]
    static let firmwareNumberKeys: Set<String> = [
        "accuracy", "activeStage", "ageMs", "alertMode",
        "applyErrorCode", "attempt", "blockLoadMs", "bootSequence",
        "bytes", "bytesLimit", "bytesPerSecond", "chunk",
        "commandClass", "completedStage", "connectDurationMs", "connectionGeneration",
        "consecutiveEarlyFailures", "coredumpBytes", "cutoffSequence", "decisionSequence",
        "discardedBytes", "droppedCount", "durableSequence", "durationMs",
        "emissionSequence", "enqueuedCount", "errorCode", "eventCount",
        "eventsPerSecond", "filteredCount", "firmwareBuild", "firstMissingUptimeMs",
        "firstSequence", "formatVersion", "frameCount", "frameSkippedCount",
        "freeInternalBytes", "freePsramBytes", "generation", "highWater",
        "highWaterBytes", "httpStatus", "importedCount", "largestInternalBytes",
        "lastFailureCompletedStage", "lastFailureResetReason", "lastFailureStage", "lastGapMs",
        "lastMissingUptimeMs", "lastSequence", "latencyMs", "leaseGeneration",
        "mapDetail", "mapProgressMs", "markerSequence", "maxQueueDepth",
        "maximumGapMs", "members", "messageBytes", "nativeReportCount",
        "oversizedCount", "partialBytes", "policyDurationMs", "policyExpiresAtEpochMs",
        "policyGeneration", "profileVersion", "queueBytes", "queueDepth",
        "rateLimitedCount", "rejectedCount", "rejectedFieldCount", "remainingChunks",
        "replacedCount", "resetReason", "retries", "rideGeneration",
        "runtimeBootSequence", "sampleCount", "sampledCount", "samplingIntervalMs",
        "schemaVersion", "segmentCount", "sequence", "sourceHealthMask",
        "stackHighWaterBytes", "storageErrorCount", "tlsDurationMs", "uiProgressMs",
        "underlyingErrorCode", "visitedEntries", "watchSequence", "watchUptimeMs",
        "watchdogCoreMask", "watchdogUptimeMs", "writerDelayMs", "writerDetail",
        "writerProgressMs", "writtenCount",
    ]
    static let firmwareBooleanKeys: Set<String> = [
        "accuracyAvailable", "active", "authorized", "autoPauseEnabled",
        "available", "background", "clockSynchronized", "connectCompleted",
        "connectStarted", "connectionReused", "crashAvailable", "diagnosticHold",
        "fallback", "fixValid", "localAccessorySubnet", "navigating",
        "pendingControl", "proxyConnection", "ready", "recorderReady",
        "remoteEndpointMatched", "rideDetectionArmed", "routeLoaded", "safeMode",
        "sessionPresent", "simulation", "speedAvailable", "tlsCompleted",
        "tlsStarted", "viewingMap", "waitedForConnectivity", "workoutActive",
    ]
    static func isAllowed(_ key: String) -> Bool {
        allowedKeys.contains(key)
    }

    static func isJSONBoolean(_ value: Any?) -> Bool {
        guard let value else { return false }
        return CFGetTypeID(value as CFTypeRef) == CFBooleanGetTypeID()
    }

    static func isFirmwareFieldTypeValid(key: String, value: Any) -> Bool {
        if firmwareNumberKeys.contains(key) {
            return value is NSNumber && !isJSONBoolean(value)
        }
        if firmwareBooleanKeys.contains(key) {
            return isJSONBoolean(value)
        }
        return value is String
    }
}
