// Generated by tools/generate_diagnostics_contract.py. Do not edit.
import Foundation
nonisolated enum DiagnosticsSchema {
    static let registryVersion = 2
    static let digest = "548d3389225598c84156b57458ea2120660ffa6c72639abe4496bc1ce2def98d"
    static let instrumentedMask: UInt32 = 5814230
    static let domains: [String] = [
        "audio", "ble", "boot", "display",
        "gps", "http", "lifecycle", "logger",
        "map", "memory", "navigation", "ota",
        "power", "rideAutomation", "sensor", "storage",
        "tasks", "tls", "touch", "transfer",
        "user", "wifi", "workout",
    ]
    static let levels: [String] = [
        "trace", "debug", "info", "warning",
        "error", "fatal",
    ]
    static func mask(for domain: String) -> UInt32 {
        guard let index = domains.firstIndex(of: domain) else { return 0 }
        return UInt32(1) << index
    }
}
