// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;

// UI Components - accessible from main.cpp
extern lv_obj_t *ui_LabelBLEStatus;
extern lv_obj_t *ui_LabelHeapFree;
extern lv_obj_t *ui_LabelPSRAMFree;
extern lv_obj_t *ui_LabelDistance;
extern lv_obj_t *ui_LabelInstruction;
extern lv_obj_t *ui_IconPlaceholder;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

