// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_LabelBLEStatus = NULL;
lv_obj_t *ui_LabelHeapFree = NULL;
lv_obj_t *ui_LabelPSRAMFree = NULL;
lv_obj_t *ui_LabelDistance = NULL;
lv_obj_t *ui_LabelInstruction = NULL;
lv_obj_t *ui_IconPlaceholder = NULL;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

// ========== Device Status Section (Top) ==========

// BLE Connection Status
ui_LabelBLEStatus = lv_label_create(ui_Screen1);
lv_obj_set_width(ui_LabelBLEStatus, LV_SIZE_CONTENT);
lv_obj_set_height(ui_LabelBLEStatus, LV_SIZE_CONTENT);
lv_obj_set_x(ui_LabelBLEStatus, 0);
lv_obj_set_y(ui_LabelBLEStatus, -190);
lv_obj_set_align(ui_LabelBLEStatus, LV_ALIGN_CENTER);
lv_label_set_text(ui_LabelBLEStatus, "BLE: Disconnected");
lv_obj_set_style_text_color(ui_LabelBLEStatus, lv_color_hex(0xFF6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBLEStatus, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

// Heap Memory Status
ui_LabelHeapFree = lv_label_create(ui_Screen1);
lv_obj_set_width(ui_LabelHeapFree, LV_SIZE_CONTENT);
lv_obj_set_height(ui_LabelHeapFree, LV_SIZE_CONTENT);
lv_obj_set_x(ui_LabelHeapFree, -80);
lv_obj_set_y(ui_LabelHeapFree, -150);
lv_obj_set_align(ui_LabelHeapFree, LV_ALIGN_CENTER);
lv_label_set_text(ui_LabelHeapFree, "Heap: -- KB");
lv_obj_set_style_text_color(ui_LabelHeapFree, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHeapFree, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

// PSRAM Memory Status
ui_LabelPSRAMFree = lv_label_create(ui_Screen1);
lv_obj_set_width(ui_LabelPSRAMFree, LV_SIZE_CONTENT);
lv_obj_set_height(ui_LabelPSRAMFree, LV_SIZE_CONTENT);
lv_obj_set_x(ui_LabelPSRAMFree, 80);
lv_obj_set_y(ui_LabelPSRAMFree, -150);
lv_obj_set_align(ui_LabelPSRAMFree, LV_ALIGN_CENTER);
lv_label_set_text(ui_LabelPSRAMFree, "PSRAM: -- KB");
lv_obj_set_style_text_color(ui_LabelPSRAMFree, lv_color_hex(0x00D4FF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPSRAMFree, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

// ========== Navigation Section (Center) ==========

// Icon/Arrow Placeholder (Large circular placeholder)
ui_IconPlaceholder = lv_obj_create(ui_Screen1);
lv_obj_set_width(ui_IconPlaceholder, 120);
lv_obj_set_height(ui_IconPlaceholder, 120);
lv_obj_set_x(ui_IconPlaceholder, 0);
lv_obj_set_y(ui_IconPlaceholder, -20);
lv_obj_set_align(ui_IconPlaceholder, LV_ALIGN_CENTER);
lv_obj_clear_flag(ui_IconPlaceholder, LV_OBJ_FLAG_SCROLLABLE);
lv_obj_set_style_radius(ui_IconPlaceholder, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_IconPlaceholder, lv_color_hex(0x2196F3), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_IconPlaceholder, lv_color_hex(0x1976D2), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_IconPlaceholder, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

// Distance Label (Large, below icon)
ui_LabelDistance = lv_label_create(ui_Screen1);
lv_obj_set_width(ui_LabelDistance, LV_SIZE_CONTENT);
lv_obj_set_height(ui_LabelDistance, LV_SIZE_CONTENT);
lv_obj_set_x(ui_LabelDistance, 0);
lv_obj_set_y(ui_LabelDistance, 80);
lv_obj_set_align(ui_LabelDistance, LV_ALIGN_CENTER);
lv_label_set_text(ui_LabelDistance, "-- m");
lv_obj_set_style_text_color(ui_LabelDistance, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelDistance, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

// Instruction Label (Below distance)
ui_LabelInstruction = lv_label_create(ui_Screen1);
lv_obj_set_width(ui_LabelInstruction, 400);
lv_obj_set_height(ui_LabelInstruction, LV_SIZE_CONTENT);
lv_obj_set_x(ui_LabelInstruction, 0);
lv_obj_set_y(ui_LabelInstruction, 150);
lv_obj_set_align(ui_LabelInstruction, LV_ALIGN_CENTER);
lv_label_set_text(ui_LabelInstruction, "Waiting for navigation...");
lv_obj_set_style_text_color(ui_LabelInstruction, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelInstruction, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelInstruction, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
lv_label_set_long_mode(ui_LabelInstruction, LV_LABEL_LONG_WRAP);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1 = NULL;
ui_LabelBLEStatus = NULL;
ui_LabelHeapFree = NULL;
ui_LabelPSRAMFree = NULL;
ui_LabelDistance = NULL;
ui_LabelInstruction = NULL;
ui_IconPlaceholder = NULL;

}
