// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;
lv_obj_t *ui_LabelBLEStatus = NULL;
lv_obj_t *ui_LabelHeapFree = NULL;
lv_obj_t *ui_LabelPSRAMFree = NULL;
lv_obj_t *ui_LabelDistance = NULL;
lv_obj_t *ui_LabelInstruction = NULL;
lv_obj_t *ui_IconPlaceholder = NULL;

// Canvas buffer for drawing arrows
static lv_color_t *canvas_buf = NULL;

// --- Helper: Draw a filled rounded arrowhead ---
// We use a polygon for the head, but shaped like a wide arrow
void draw_arrow_head_poly(lv_point_t *points, int count, lv_color_t color) {
  lv_draw_rect_dsc_t draw_dsc;
  lv_draw_rect_dsc_init(&draw_dsc);
  draw_dsc.bg_color = color;
  draw_dsc.bg_opa = LV_OPA_COVER;
  lv_canvas_draw_polygon(ui_IconPlaceholder, points, count, &draw_dsc);
}

// --- Arrow Drawing Functions ---

void draw_up_arrow(lv_color_t color) {
  if (!ui_IconPlaceholder || !canvas_buf)
    return;

  lv_canvas_fill_bg(ui_IconPlaceholder, lv_color_make(0, 0, 0), LV_OPA_COVER);

  lv_draw_line_dsc_t line_dsc;
  lv_draw_line_dsc_init(&line_dsc);
  line_dsc.color = color;
  line_dsc.width = 14;
  line_dsc.round_start = true;
  line_dsc.round_end = false;
  line_dsc.opa = LV_OPA_COVER;

  // Code-LEFT points Screen-UP
  lv_point_t points_shaft[] = {{70, 40}, {30, 40}};
  lv_canvas_draw_line(ui_IconPlaceholder, points_shaft, 2, &line_dsc);

  static lv_point_t head_points[] = {
      {10, 40}, // Tip
      {36, 22}, // Top
      {36, 58}  // Bottom
  };
  draw_arrow_head_poly(head_points, 3, color);
}

void draw_left_arrow(lv_color_t color) {
  if (!ui_IconPlaceholder || !canvas_buf)
    return;

  lv_canvas_fill_bg(ui_IconPlaceholder, lv_color_make(0, 0, 0), LV_OPA_COVER);

  lv_draw_line_dsc_t line_dsc;
  lv_draw_line_dsc_init(&line_dsc);
  line_dsc.color = color;
  line_dsc.width = 14;
  line_dsc.round_start = true;
  line_dsc.round_end = false;
  line_dsc.opa = LV_OPA_COVER;

  // Code-DOWN points Screen-LEFT
  lv_point_t points_shaft[] = {{40, 10}, {40, 50}};
  lv_canvas_draw_line(ui_IconPlaceholder, points_shaft, 2, &line_dsc);

  static lv_point_t head_points[] = {
      {40, 70}, // Tip
      {22, 44}, // Left
      {58, 44}  // Right
  };
  draw_arrow_head_poly(head_points, 3, color);
}

void draw_right_arrow(lv_color_t color) {
  if (!ui_IconPlaceholder || !canvas_buf)
    return;

  lv_canvas_fill_bg(ui_IconPlaceholder, lv_color_make(0, 0, 0), LV_OPA_COVER);

  lv_draw_line_dsc_t line_dsc;
  lv_draw_line_dsc_init(&line_dsc);
  line_dsc.color = color;
  line_dsc.width = 14;
  line_dsc.round_start = true;
  line_dsc.round_end = false;
  line_dsc.opa = LV_OPA_COVER;

  // Code-UP points Screen-RIGHT
  lv_point_t points_shaft[] = {{40, 70}, {40, 30}};
  lv_canvas_draw_line(ui_IconPlaceholder, points_shaft, 2, &line_dsc);

  static lv_point_t head_points[] = {
      {40, 10}, // Tip
      {22, 36}, // Left
      {58, 36}  // Right
  };
  draw_arrow_head_poly(head_points, 3, color);
}

void draw_u_turn_arrow(lv_color_t color) {
  if (!ui_IconPlaceholder || !canvas_buf)
    return;

  lv_canvas_fill_bg(ui_IconPlaceholder, lv_color_make(0, 0, 0), LV_OPA_COVER);

  lv_draw_line_dsc_t line_dsc;
  lv_draw_line_dsc_init(&line_dsc);
  line_dsc.color = color;
  line_dsc.width = 14;
  line_dsc.round_start = true;
  line_dsc.round_end = false;
  line_dsc.opa = LV_OPA_COVER;

  lv_draw_arc_dsc_t arc_dsc;
  lv_draw_arc_dsc_init(&arc_dsc);
  arc_dsc.color = color;
  arc_dsc.width = 14;
  arc_dsc.rounded = false;
  arc_dsc.opa = LV_OPA_COVER;

  // Screen: UP -> Curve Left -> DOWN
  // Code (90 deg CW rotation): LEFT -> Curve Down -> RIGHT

  // 1. Bottom Horizontal (Code-LEFT)
  lv_point_t p_left[] = {{70, 25}, {35, 25}};
  lv_canvas_draw_line(ui_IconPlaceholder, p_left, 2, &line_dsc);

  // 2. The Curve (Code-DOWN side)
  // Center (35, 45), Radius 20.
  // From 270 (Top/Right-start) to 90 (Bottom/Right-end) via 180
  // (Left/DOWN-side)
  lv_canvas_draw_arc(ui_IconPlaceholder, 35, 45, 20, 90, 270, &arc_dsc);

  // 3. Top Horizontal (Code-RIGHT)
  lv_point_t p_right[] = {{35, 65}, {45, 65}};
  lv_canvas_draw_line(ui_IconPlaceholder, p_right, 2, &line_dsc);

  // 4. Arrow Head (Pointing Code-RIGHT)
  static lv_point_t head_points[] = {
      {70, 65}, // Tip
      {46, 49}, // Top wing
      {46, 81}  // Bottom wing
  };
  draw_arrow_head_poly(head_points, 3, color);
}

// event functions
// build functions

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000),
                            LV_PART_MAIN | LV_STATE_DEFAULT);

  // ========== Device Status Section (Top) ==========

  // BLE Connection Status
  ui_LabelBLEStatus = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_LabelBLEStatus, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_LabelBLEStatus, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_LabelBLEStatus, 0);
  lv_obj_set_y(ui_LabelBLEStatus, -190);
  lv_obj_set_align(ui_LabelBLEStatus, LV_ALIGN_CENTER);
  lv_label_set_text(ui_LabelBLEStatus, "BLE: Disconnected");
  lv_obj_set_style_text_color(ui_LabelBLEStatus, lv_color_hex(0xFF6B6B),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_LabelBLEStatus, &lv_font_montserrat_18,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  // Heap Memory Status
  ui_LabelHeapFree = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_LabelHeapFree, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_LabelHeapFree, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_LabelHeapFree, -80);
  lv_obj_set_y(ui_LabelHeapFree, -150);
  lv_obj_set_align(ui_LabelHeapFree, LV_ALIGN_CENTER);
  lv_label_set_text(ui_LabelHeapFree, "Heap: -- KB");
  lv_obj_set_style_text_color(ui_LabelHeapFree, lv_color_hex(0x00D4FF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_LabelHeapFree, &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  // PSRAM Memory Status
  ui_LabelPSRAMFree = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_LabelPSRAMFree, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_LabelPSRAMFree, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_LabelPSRAMFree, 80);
  lv_obj_set_y(ui_LabelPSRAMFree, -150);
  lv_obj_set_align(ui_LabelPSRAMFree, LV_ALIGN_CENTER);
  lv_label_set_text(ui_LabelPSRAMFree, "PSRAM: -- KB");
  lv_obj_set_style_text_color(ui_LabelPSRAMFree, lv_color_hex(0x00D4FF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_LabelPSRAMFree, &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  // ========== Navigation Section (Center) ==========

  // Navigation Arrow/Icon Display (Canvas for vector arrows)
  ui_IconPlaceholder = lv_canvas_create(ui_Screen1);
  lv_obj_set_width(ui_IconPlaceholder, 80);
  lv_obj_set_height(ui_IconPlaceholder, 80);
  lv_obj_set_x(ui_IconPlaceholder, 0);
  lv_obj_set_y(ui_IconPlaceholder, -20);
  lv_obj_set_align(ui_IconPlaceholder, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_IconPlaceholder, LV_OBJ_FLAG_SCROLLABLE);

  // Allocate canvas buffer (80x80 pixels) with error checking
  canvas_buf = (lv_color_t *)lv_mem_alloc(80 * 80 * sizeof(lv_color_t));
  if (canvas_buf != NULL) {
    lv_canvas_set_buffer(ui_IconPlaceholder, canvas_buf, 80, 80,
                         LV_IMG_CF_TRUE_COLOR);
    lv_canvas_fill_bg(ui_IconPlaceholder, lv_color_make(0, 0, 0),
                      LV_OPA_COVER);
  } else {
    // Canvas buffer allocation failed - hide the placeholder
    lv_obj_add_flag(ui_IconPlaceholder, LV_OBJ_FLAG_HIDDEN);
  }

  // Distance Label (Large, below icon)
  ui_LabelDistance = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_LabelDistance, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_LabelDistance, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_LabelDistance, 0);
  lv_obj_set_y(ui_LabelDistance, 80);
  lv_obj_set_align(ui_LabelDistance, LV_ALIGN_CENTER);
  lv_label_set_text(ui_LabelDistance, "-- m");
  lv_obj_set_style_text_color(ui_LabelDistance, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_LabelDistance, &lv_font_montserrat_48,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  // Instruction Label (Below distance)
  ui_LabelInstruction = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_LabelInstruction, 400);
  lv_obj_set_height(ui_LabelInstruction, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_LabelInstruction, 0);
  lv_obj_set_y(ui_LabelInstruction, 150);
  lv_obj_set_align(ui_LabelInstruction, LV_ALIGN_CENTER);
  lv_label_set_text(ui_LabelInstruction, "Waiting for navigation...");
  lv_obj_set_style_text_color(ui_LabelInstruction, lv_color_hex(0xCCCCCC),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_LabelInstruction, &lv_font_montserrat_20,
                             LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_align(ui_LabelInstruction, LV_TEXT_ALIGN_CENTER,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_label_set_long_mode(ui_LabelInstruction, LV_LABEL_LONG_WRAP);
}

void ui_Screen1_screen_destroy(void) {
  if (ui_Screen1)
    lv_obj_del(ui_Screen1);

  // Free canvas buffer
  if (canvas_buf) {
    lv_mem_free(canvas_buf);
    canvas_buf = NULL;
  }

  // NULL screen variables
  ui_Screen1 = NULL;
  ui_LabelBLEStatus = NULL;
  ui_LabelHeapFree = NULL;
  ui_LabelPSRAMFree = NULL;
  ui_LabelDistance = NULL;
  ui_LabelInstruction = NULL;
  ui_IconPlaceholder = NULL;
}
