// Generated by tools/generate_ride_ble_contract.py. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace ride_ble_protocol_generated {
inline constexpr char SERVICE_UUID[] = "9D7B3F30-3F6A-4D1C-9F6D-1FBF0E8B1800";
inline constexpr char NAVIGATION_UUID[] = "2A6E";
inline constexpr char ROUTE_UUID[] = "2A6F";
inline constexpr char GPS_UUID[] = "2A72";
inline constexpr char SETTINGS_UUID[] = "2A73";
inline constexpr char AUTH_UUID[] = "9D7B3F30-3F6A-4D1C-9F6D-1FBF0E8B1002";
inline constexpr char WORKOUT_UUID[] = "9D7B3F30-3F6A-4D1C-9F6D-1FBF0E8B1003";
inline constexpr char RIDE_AUTOMATION_UUID[] = "9D7B3F30-3F6A-4D1C-9F6D-1FBF0E8B1004";
inline constexpr std::size_t PROTECTED_FRAME_OVERHEAD = 22;
inline constexpr uint8_t CAPABILITY_SCHEMA_VERSION = 1;
inline constexpr uint8_t CURRENT_CLIENT_VERSION = 21;
inline constexpr uint32_t DEVICE_SOUNDS_FEATURE = 1UL << 0;
inline constexpr uint8_t DEVICE_SOUNDS_MINIMUM_CLIENT_VERSION = 1;
inline constexpr uint32_t POWER_BUTTON_HONK_FEATURE = 1UL << 1;
inline constexpr uint8_t POWER_BUTTON_HONK_MINIMUM_CLIENT_VERSION = 1;
inline constexpr uint32_t POWER_BUTTON_HONK_ACK_FEATURE = 1UL << 2;
inline constexpr uint8_t POWER_BUTTON_HONK_ACK_MINIMUM_CLIENT_VERSION = 1;
inline constexpr uint32_t INDEPENDENT_MAP_PROFILES_FEATURE = 1UL << 3;
inline constexpr uint8_t INDEPENDENT_MAP_PROFILES_MINIMUM_CLIENT_VERSION = 1;
inline constexpr uint32_t EXTENDED_MAP_VISIBILITY_FEATURE = 1UL << 4;
inline constexpr uint8_t EXTENDED_MAP_VISIBILITY_MINIMUM_CLIENT_VERSION = 1;
inline constexpr uint32_t BATTERY_STATUS_SCREEN_FEATURE = 1UL << 5;
inline constexpr uint8_t BATTERY_STATUS_SCREEN_MINIMUM_CLIENT_VERSION = 1;
inline constexpr uint32_t DESTINATION_PICKER_FEATURE = 1UL << 6;
inline constexpr uint8_t DESTINATION_PICKER_MINIMUM_CLIENT_VERSION = 1;
inline constexpr uint32_t WORKOUT_TELEMETRY_FEATURE = 1UL << 7;
inline constexpr uint8_t WORKOUT_TELEMETRY_MINIMUM_CLIENT_VERSION = 1;
inline constexpr uint32_t STREET_LABELS_FEATURE = 1UL << 8;
inline constexpr uint8_t STREET_LABELS_MINIMUM_CLIENT_VERSION = 10;
inline constexpr uint32_t BIRDS_EYE_MAP_NAVIGATION_FEATURE = 1UL << 9;
inline constexpr uint8_t BIRDS_EYE_MAP_NAVIGATION_MINIMUM_CLIENT_VERSION = 10;
inline constexpr uint32_t BIRDS_EYE_PERSPECTIVE_FEATURE = 1UL << 10;
inline constexpr uint8_t BIRDS_EYE_PERSPECTIVE_MINIMUM_CLIENT_VERSION = 10;
inline constexpr uint32_t BIRDS_EYE_STRONGER_PERSPECTIVE_FEATURE = 1UL << 11;
inline constexpr uint8_t BIRDS_EYE_STRONGER_PERSPECTIVE_MINIMUM_CLIENT_VERSION = 10;
inline constexpr uint32_t OSM_3D_BUILDINGS_FEATURE = 1UL << 12;
inline constexpr uint8_t OSM_3D_BUILDINGS_MINIMUM_CLIENT_VERSION = 10;
inline constexpr uint32_t EXPLICIT_INVALID_GPS_HEADING_FEATURE = 1UL << 13;
inline constexpr uint8_t EXPLICIT_INVALID_GPS_HEADING_MINIMUM_CLIENT_VERSION = 11;
inline constexpr uint32_t SCOPED_WATCH_CONTROLLER_FEATURE = 1UL << 14;
inline constexpr uint8_t SCOPED_WATCH_CONTROLLER_MINIMUM_CLIENT_VERSION = 12;
inline constexpr uint32_t RIDE_AUTOMATION_V2_FEATURE = 1UL << 15;
inline constexpr uint8_t RIDE_AUTOMATION_V2_MINIMUM_CLIENT_VERSION = 13;
inline constexpr uint32_t REMOTE_DEVICE_DEBUG_FEATURE = 1UL << 16;
inline constexpr uint8_t REMOTE_DEVICE_DEBUG_MINIMUM_CLIENT_VERSION = 14;
inline constexpr uint32_t GPS_POSITION_QUALITY_V1_FEATURE = 1UL << 17;
inline constexpr uint8_t GPS_POSITION_QUALITY_V1_MINIMUM_CLIENT_VERSION = 15;
inline constexpr uint32_t RENDERER_DIAGNOSTICS_FEATURE = 1UL << 18;
inline constexpr uint8_t RENDERER_DIAGNOSTICS_MINIMUM_CLIENT_VERSION = 16;
inline constexpr uint32_t AUTOMATIC_DISPLAY_OFF_FEATURE = 1UL << 19;
inline constexpr uint8_t AUTOMATIC_DISPLAY_OFF_MINIMUM_CLIENT_VERSION = 16;
inline constexpr uint32_t RIDE_DIAGNOSTICS_FEATURE = 1UL << 20;
inline constexpr uint8_t RIDE_DIAGNOSTICS_MINIMUM_CLIENT_VERSION = 18;
inline constexpr uint32_t DETAILED_RIDE_DIAGNOSTICS_FEATURE = 1UL << 21;
inline constexpr uint8_t DETAILED_RIDE_DIAGNOSTICS_MINIMUM_CLIENT_VERSION = 19;
inline constexpr uint32_t RIDE_DELIVERY_ACK_FEATURE = 1UL << 22;
inline constexpr uint8_t RIDE_DELIVERY_ACK_MINIMUM_CLIENT_VERSION = 20;
inline constexpr uint32_t MAP_POIS_FEATURE = 1UL << 23;
inline constexpr uint8_t MAP_POIS_MINIMUM_CLIENT_VERSION = 21;
inline constexpr char APPLICATION_COMMAND_MAGIC[] = "RCM1";
inline constexpr char APPLICATION_ACK_MAGIC[] = "RAK1";
inline constexpr uint8_t APPLICATION_DELIVERY_VERSION = 1;
inline constexpr std::size_t APPLICATION_COMMAND_HEADER_BYTES = 28;
inline constexpr std::size_t APPLICATION_ACK_BYTES = 32;
inline constexpr uint8_t MAXIMUM_APPLICATION_GROUP_MEMBERS = 8;
inline constexpr std::size_t COMPLETED_APPLICATION_REPLAY_WINDOW = 8;
inline constexpr char APPLICATION_COMMAND_GOLDEN_HEX[] = "52434d310102010300112233445566778899aabbccddeeff78563412aabb";
inline constexpr char APPLICATION_ACK_GOLDEN_HEX[] = "52414b310102000000112233445566778899aabbccddeeff7856341209000000";

enum class ProtectedChannel : uint8_t {
  Auth = 1,
  Navigation = 2,
  Route = 3,
  Gps = 4,
  Settings = 5,
  Workout = 6,
  RideAutomation = 7,
};

enum class ControllerRole : uint8_t {
  None = 0,
  Owner = 1,
  WatchRide = 2,
};

enum class ApplicationCommandType : uint8_t {
  NavigationClear = 1,
  WorkoutState = 2,
};

enum class ApplicationResult : uint8_t {
  Success = 0,
  Stale = 1,
  Busy = 2,
  Unauthorized = 3,
  Malformed = 4,
  ResourceRejected = 5,
};

} // namespace ride_ble_protocol_generated
