// Generated by tools/generate_ride_ble_contract.py. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>
namespace workout_zone_wire {
inline constexpr uint32_t ZONE_WIRE_VERSION = 1;
inline constexpr uint32_t FRAME_KIND = 5;
inline constexpr uint32_t HEADER_BYTES = 32;
inline constexpr uint32_t MAXIMUM_ZONES = 9;
inline constexpr uint32_t MINIMUM_ZONES = 3;
inline constexpr uint32_t MAXIMUM_FRAME_BYTES = 132;
inline constexpr uint32_t HEART_RATE_MAXIMUM_AGE_MS = 30000;
inline constexpr uint32_t POWER_MAXIMUM_AGE_MS = 5000;
inline constexpr uint32_t STREAM_MAXIMUM_AGE_MS = 10000;
inline constexpr uint32_t FLAG_FINAL = 1;
inline constexpr uint32_t FLAG_LOWER_BOUND_ZERO = 2;
inline constexpr uint32_t FLAG_DURATIONS = 4;
inline constexpr uint32_t METRIC_HEART_RATE = 1;
inline constexpr uint32_t METRIC_CYCLING_POWER = 2;
inline constexpr uint32_t SOURCE_BICINO = 0;
inline constexpr uint32_t SOURCE_HEALTHKIT_SYSTEM = 1;
inline constexpr uint32_t SOURCE_HEALTHKIT_USER = 2;
inline constexpr uint32_t SOURCE_HEALTHKIT_APP = 3;
inline constexpr uint32_t SOURCE_HEALTHKIT_UNKNOWN = 4;
inline constexpr uint32_t OFFSET_KIND = 0;
inline constexpr uint32_t OFFSET_VERSION = 1;
inline constexpr uint32_t OFFSET_METRIC = 2;
inline constexpr uint32_t OFFSET_SOURCE = 3;
inline constexpr uint32_t OFFSET_FLAGS = 4;
inline constexpr uint32_t OFFSET_COUNT = 5;
inline constexpr uint32_t OFFSET_CURRENT_ZONE = 6;
inline constexpr uint32_t OFFSET_STATE = 7;
inline constexpr uint32_t OFFSET_SESSION_TOKEN = 8;
inline constexpr uint32_t OFFSET_SAMPLE_AGE_MS = 10;
inline constexpr uint32_t OFFSET_SEQUENCE = 12;
inline constexpr uint32_t OFFSET_SESSION_UUID = 16;
inline constexpr uint32_t OFFSET_BOUNDARIES = 32;
} // namespace workout_zone_wire
