#!/usr/bin/env python3
"""Generate all diagnostics scalar/level/domain vocabularies from the reviewed registry.

The retained JSONL wire format is intentionally unchanged. New control and
acquisition APIs are v2; v1 evidence stays readable without rewriting its bytes.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / 'protocol/diagnostics/contract-v2.json'
SWIFT_FIELD_HELPERS = '    static func isAllowed(_ key: String) -> Bool {\n        allowedKeys.contains(key)\n    }\n\n    static func isJSONBoolean(_ value: Any?) -> Bool {\n        guard let value else { return false }\n        return CFGetTypeID(value as CFTypeRef) == CFBooleanGetTypeID()\n    }\n\n    static func isFirmwareFieldTypeValid(key: String, value: Any) -> Bool {\n        if firmwareNumberKeys.contains(key) {\n            return value is NSNumber && !isJSONBoolean(value)\n        }\n        if firmwareBooleanKeys.contains(key) {\n            return isJSONBoolean(value)\n        }\n        return value is String\n    }\n}'


def replace_block(text: str, start: str, end: str, content: str) -> str:
    if text.count(start) != 1 or text.count(end) != 1:
        raise ValueError(f'Expected one generated block: {start}')
    left, rest = text.split(start, 1)
    _, right = rest.split(end, 1)
    return left + start + '\n' + content.rstrip() + '\n' + end + right


def quoted_rows(keys: list[str], indent: str = '    ') -> str:
    return '\n'.join(indent + ', '.join(json.dumps(k) for k in keys[i:i+4]) + ','
                     for i in range(0, len(keys), 4))


def outputs() -> dict[Path, str]:
    raw = CONTRACT.read_bytes()
    c = json.loads(raw)
    if c['schema'] != 2 or c['eventWireSchema'] != 1:
        raise ValueError('Unsupported contract version')
    for key, field in c['fields'].items():
        if not re.fullmatch(r'[a-z][A-Za-z0-9]{0,63}', key):
            raise ValueError(f'Invalid field: {key}')
        if field['type'] not in {'string','number','boolean'} or field['privacy'] != 'diagnostic':
            raise ValueError(f'Unreviewed field: {key}')
    if len(set(c['levels'])) != len(c['levels']) or len(set(c['categories'])) != len(c['categories']):
        raise ValueError('Duplicate level or category')
    all_keys = sorted(c['fields'])
    numbers = [k for k in all_keys if c['fields'][k]['type'] == 'number']
    booleans = [k for k in all_keys if c['fields'][k]['type'] == 'boolean']
    result: dict[Path,str] = {}
    p = ROOT / 'tools/ride_diagnostics.py'
    text = p.read_text()
    enums = '\n'.join(f'{name} = {{\n{quoted_rows(vals)}\n}}' for name, vals in
                      [('ALLOWED_LEVELS',c['levels']),('ALLOWED_CATEGORIES',c['categories'])])
    text = replace_block(text, '# BEGIN GENERATED DIAGNOSTICS ENUMS', '# END GENERATED DIAGNOSTICS ENUMS', enums)
    fields = '\n'.join(f'{name} = {{\n{quoted_rows(vals)}\n}}' for name, vals in
                       [('ALLOWED_FIELD_KEYS',all_keys),('FIRMWARE_NUMBER_FIELD_KEYS',numbers),('FIRMWARE_BOOLEAN_FIELD_KEYS',booleans)])
    result[p] = replace_block(text, '# BEGIN GENERATED DIAGNOSTICS FIELDS', '# END GENERATED DIAGNOSTICS FIELDS', fields)
    p = ROOT / 'ios-app/BikeComputer/BikeComputer/Utilities/RideDiagnostics.swift'
    text = p.read_text()
    enums = '\n\n'.join(f'nonisolated enum {name}: String, Codable, CaseIterable {{\n' +
                         '\n'.join('    case '+v for v in vals)+'\n}' for name, vals in
                         [('RideDiagnosticLevel',c['levels']),('RideDiagnosticCategory',c['categories'])])
    text = replace_block(text, '// BEGIN GENERATED DIAGNOSTICS ENUMS', '// END GENERATED DIAGNOSTICS ENUMS', enums)
    result[p] = text
    swift_fields = '\n'.join(f'    static let {name}: Set<String> = [\n{quoted_rows(vals,"        ")}\n    ]' for name, vals in
                       [('allowedKeys',all_keys),('firmwareNumberKeys',numbers),('firmwareBooleanKeys',booleans)])
    p = ROOT / 'esp32/lib/ride_diagnostics/ride_diagnostics_format.hpp'
    text = p.read_text()
    text = replace_block(text, '// BEGIN GENERATED DIAGNOSTICS FIELDS', '// END GENERATED DIAGNOSTICS FIELDS',
                         'constexpr const char *kAllowedFieldKeys[] = {\n'+quoted_rows(all_keys)+'\n};')
    fields = '\n'.join(f'static constexpr const char *{name}[] = {{\n{quoted_rows(vals)}\n}};' for name, vals in
                       [('kNumberKeys',numbers),('kBooleanKeys',booleans)])
    result[p] = replace_block(text, '// BEGIN GENERATED DIAGNOSTICS TYPES', '// END GENERATED DIAGNOSTICS TYPES', fields)
    # The compact runtime policy is shared by firmware and host fixtures.
    fingerprint=hashlib.sha256(raw).hexdigest()
    p=ROOT / 'esp32/lib/ride_diagnostics/diagnostics_contract.generated.hpp'
    result[p] = ('// Generated by tools/generate_diagnostics_contract.py; do not edit.\n#pragma once\n'
                 '#include <cstddef>\n#include <cstdint>\nnamespace bicino_diagnostics::contract {\n'
                 f'constexpr const char *kSha256 = "{fingerprint}";\n'
                 'constexpr const char *kDomains[] = {\n'+quoted_rows(c['categories'])+'\n};\n'
                 'constexpr std::size_t kDomainCount = sizeof(kDomains) / sizeof(kDomains[0]);\n'
                 'constexpr const char *kLevels[] = {\n'+quoted_rows(c['levels'])+'\n};\n'
                 + ''.join(f'constexpr uint32_t k{k[0].upper()+k[1:]} = {v}U;\n' for k,v in c['limits'].items())+
                 '} // namespace bicino_diagnostics::contract\n')
    p=ROOT / 'ios-app/BikeComputer/BikeComputer/Utilities/DiagnosticsContractV2.generated.swift'
    profiles = {name: data['levels'] for name,data in c['profiles'].items()}
    profile_text = ',\n'.join('        '+json.dumps(name)+': [' + ', '.join(json.dumps(k)+': '+json.dumps(v) for k,v in values.items()) + ']' for name,values in profiles.items() if values)
    result[p] = ('// Generated by tools/generate_diagnostics_contract.py; do not edit.\n'
                 'import Foundation\nimport CoreFoundation\n\nnonisolated enum DiagnosticsContractV2 {\n'
                 f'    static let sha256 = "{fingerprint}"\n'
                 '    static let domains = [' + ', '.join(json.dumps(v) for v in c['categories']) + ']\n'
                 '    static let levels = [' + ', '.join(json.dumps(v) for v in c['levels']) + ']\n'
                 f'    static let maximumCaptureSeconds: UInt32 = {c["limits"]["maximumCaptureSeconds"]}\n'
                 '    static let profiles: [String: [String: String]] = [\n'
                 '        "baseline": [:],\n'+profile_text+'\n    ]\n}\n\n' +
                 'nonisolated enum RideDiagnosticsFieldPolicy {\n' + swift_fields + '\n' + SWIFT_FIELD_HELPERS + '\n')
    p=ROOT / 'tools/bicino_diagnostics/contract.generated.json'
    result[p]=json.dumps(c|{'sha256':fingerprint},indent=2,sort_keys=True)+'\n'
    return result


def main() -> int:
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check',action='store_true')
    args=ap.parse_args()
    mismatches=[]
    for path,text in outputs().items():
        if path.exists() and path.read_text()==text: continue
        if args.check: mismatches.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(text)
    if mismatches:
        ap.exit(1,'Stale diagnostics contract: '+', '.join(mismatches)+'\n')
    return 0

if __name__=='__main__': raise SystemExit(main())
