#!/usr/bin/env python3
"""Generate the Swift/C++ fixed BLE contract from one reviewed JSON source."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "protocol" / "ride-ble-contract-v1.json"
SWIFT_OUTPUT = (
    ROOT
    / "ios-app"
    / "BikeComputer"
    / "RideShared"
    / "RideBLEProtocol.generated.swift"
)
CPP_OUTPUT = (
    ROOT
    / "esp32"
    / "lib"
    / "ble_navigation"
    / "ride_ble_protocol.generated.hpp"
)


def upper(name: str) -> str:
    return name.upper()


def camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(part.title() for part in parts[1:])


def pascal(name: str) -> str:
    return "".join(part.title() for part in name.split("_"))


def load_contract() -> dict:
    contract = json.loads(SOURCE.read_text(encoding="utf-8"))
    if contract.get("schema_version") != 1:
        raise SystemExit("unsupported ride BLE contract schema")
    uuid_pattern = re.compile(
        r"^(?:[0-9A-F]{4}|[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-"
        r"[0-9A-F]{4}-[0-9A-F]{12})$"
    )
    for value in [contract["service_uuid"], *contract["characteristics"].values()]:
        if not uuid_pattern.fullmatch(value):
            raise SystemExit(f"invalid uppercase UUID: {value}")
    features = contract["capabilities"]["features"]
    bits = [entry["bit"] for entry in features.values()]
    if len(bits) != len(set(bits)) or any(bit < 0 or bit > 31 for bit in bits):
        raise SystemExit("capability bits must be unique UInt32 positions")
    delivery = contract["application_delivery"]
    for key in ("command_magic", "ack_magic"):
        if len(delivery[key].encode("ascii")) != 4:
            raise SystemExit(f"{key} must be exactly four ASCII bytes")
    if delivery["command_header_bytes"] != 28 or delivery["ack_bytes"] != 32:
        raise SystemExit("application delivery v1 requires 28-byte commands and 32-byte ACKs")
    if not 1 <= delivery["maximum_group_members"] <= 8:
        raise SystemExit("application groups must contain between one and eight members")
    if delivery["completed_replay_window"] < 1:
        raise SystemExit("application replay window must retain at least one result")
    command = bytes.fromhex(delivery["golden"]["command_hex"])
    acknowledgement = bytes.fromhex(delivery["golden"]["ack_hex"])
    if len(command) < delivery["command_header_bytes"]:
        raise SystemExit("application command golden is shorter than its header")
    if len(acknowledgement) != delivery["ack_bytes"]:
        raise SystemExit("application ACK golden length does not match contract")
    command_types = set(delivery["command_types"].values())
    results = set(delivery["results"].values())
    if (
        command[:4] != delivery["command_magic"].encode("ascii")
        or acknowledgement[:4] != delivery["ack_magic"].encode("ascii")
        or command[4] != delivery["version"]
        or acknowledgement[4] != delivery["version"]
        or command[5] not in command_types
        or acknowledgement[5] not in command_types
        or acknowledgement[6] not in results
        or acknowledgement[7] != 0
        or command[7] == 0
        or command[7] > delivery["maximum_group_members"]
        or command[6] >= command[7]
        or not any(command[8:24])
        or not any(acknowledgement[8:24])
        or int.from_bytes(command[24:28], "little") == 0
        or int.from_bytes(acknowledgement[24:28], "little") == 0
    ):
        raise SystemExit("application delivery goldens violate the v1 layout")
    return contract


def render_swift(contract: dict) -> str:
    caps = contract["capabilities"]
    delivery = contract["application_delivery"]
    lines = [
        "// Generated by tools/generate_ride_ble_contract.py. Do not edit.",
        "import Foundation",
        "",
        "enum RideBLEGeneratedProtocolV1 {",
        f'    static let serviceUUID = "{contract["service_uuid"]}"',
    ]
    for name, value in contract["characteristics"].items():
        lines.append(f'    static let {camel(name)}UUID = "{value}"')
    lines.extend(
        [
            f"    static let protectedFrameOverhead = {contract['protected_frame_overhead']}",
            f'    static let capabilityRequestMagic = "{caps["request_magic"]}"',
            f'    static let capabilityResponseMagic = "{caps["response_magic"]}"',
            f"    static let capabilitySchemaVersion: UInt8 = {caps['response_schema_version']}",
            f"    static let currentClientVersion: UInt8 = {caps['current_client_version']}",
        ]
    )
    for name, entry in caps["features"].items():
        lines.append(
            f"    static let {camel(name)}Feature: UInt32 = 1 << {entry['bit']}"
        )
        lines.append(
            f"    static let {camel(name)}MinimumClientVersion: UInt8 = "
            f"{entry['minimum_client_version']}"
        )
    requests = contract["device_requests"]
    lines.extend(
        [
            f'    static let workoutStartRequestMagic = "{requests["workout_start_magic"]}"',
            f'    static let destinationRequestMagic = "{requests["destination_magic"]}"',
            f'    static let applicationCommandMagic = "{delivery["command_magic"]}"',
            f'    static let applicationAcknowledgementMagic = "{delivery["ack_magic"]}"',
            f"    static let applicationDeliveryVersion: UInt8 = {delivery['version']}",
            f"    static let applicationCommandHeaderBytes = {delivery['command_header_bytes']}",
            f"    static let applicationAcknowledgementBytes = {delivery['ack_bytes']}",
            f"    static let maximumApplicationGroupMembers = {delivery['maximum_group_members']}",
            f"    static let completedApplicationReplayWindow = {delivery['completed_replay_window']}",
            f'    static let applicationCommandGoldenHex = "{delivery["golden"]["command_hex"]}"',
            f'    static let applicationAcknowledgementGoldenHex = "{delivery["golden"]["ack_hex"]}"',
            "}",
            "",
            "enum RideBLEGeneratedProtectedChannelV1: UInt8, Sendable {",
        ]
    )
    for name, value in contract["protected_channels"].items():
        lines.append(f"    case {camel(name)} = {value}")
    lines.extend(["}", "", "enum RideBLEGeneratedControllerRoleV1: UInt8, Sendable {"])
    for name, value in contract["controller_roles"].items():
        lines.append(f"    case {camel(name)} = {value}")
    lines.extend(["}", "", "enum RideBLEApplicationCommandTypeV1: UInt8, Equatable, Sendable {"])
    for name, value in delivery["command_types"].items():
        lines.append(f"    case {camel(name)} = {value}")
    lines.extend(["}", "", "enum RideBLEApplicationResultV1: UInt8, Equatable, Sendable {"])
    for name, value in delivery["results"].items():
        lines.append(f"    case {camel(name)} = {value}")
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_cpp(contract: dict) -> str:
    caps = contract["capabilities"]
    delivery = contract["application_delivery"]
    lines = [
        "// Generated by tools/generate_ride_ble_contract.py. Do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace ride_ble_protocol_generated {",
        f'inline constexpr char SERVICE_UUID[] = "{contract["service_uuid"]}";',
    ]
    for name, value in contract["characteristics"].items():
        lines.append(f'inline constexpr char {upper(name)}_UUID[] = "{value}";')
    lines.extend(
        [
            f"inline constexpr std::size_t PROTECTED_FRAME_OVERHEAD = {contract['protected_frame_overhead']};",
            f"inline constexpr uint8_t CAPABILITY_SCHEMA_VERSION = {caps['response_schema_version']};",
            f"inline constexpr uint8_t CURRENT_CLIENT_VERSION = {caps['current_client_version']};",
        ]
    )
    for name, entry in caps["features"].items():
        lines.append(
            f"inline constexpr uint32_t {upper(name)}_FEATURE = 1UL << {entry['bit']};"
        )
        lines.append(
            f"inline constexpr uint8_t {upper(name)}_MINIMUM_CLIENT_VERSION = "
            f"{entry['minimum_client_version']};"
        )
    lines.extend(
        [
            f"inline constexpr uint16_t SOURCE_HEALTH_MASK = {sum(1 << bit for bit in contract['automation_source_health'].values())};",
            *[f"inline constexpr uint16_t SOURCE_HEALTH_{upper(name)} = 1U << {bit};" for name, bit in contract['automation_source_health'].items()],
            f'inline constexpr char APPLICATION_COMMAND_MAGIC[] = "{delivery["command_magic"]}";',
            f'inline constexpr char APPLICATION_ACK_MAGIC[] = "{delivery["ack_magic"]}";',
            f"inline constexpr uint8_t APPLICATION_DELIVERY_VERSION = {delivery['version']};",
            f"inline constexpr std::size_t APPLICATION_COMMAND_HEADER_BYTES = {delivery['command_header_bytes']};",
            f"inline constexpr std::size_t APPLICATION_ACK_BYTES = {delivery['ack_bytes']};",
            f"inline constexpr uint8_t MAXIMUM_APPLICATION_GROUP_MEMBERS = {delivery['maximum_group_members']};",
            f"inline constexpr std::size_t COMPLETED_APPLICATION_REPLAY_WINDOW = {delivery['completed_replay_window']};",
            f'inline constexpr char APPLICATION_COMMAND_GOLDEN_HEX[] = "{delivery["golden"]["command_hex"]}";',
            f'inline constexpr char APPLICATION_ACK_GOLDEN_HEX[] = "{delivery["golden"]["ack_hex"]}";',
            "",
            "enum class ProtectedChannel : uint8_t {",
        ]
    )
    for name, value in contract["protected_channels"].items():
        lines.append(f"  {pascal(name)} = {value},")
    lines.extend(["};", "", "enum class ControllerRole : uint8_t {"])
    for name, value in contract["controller_roles"].items():
        lines.append(f"  {pascal(name)} = {value},")
    lines.extend(["};", "", "enum class ApplicationCommandType : uint8_t {"])
    for name, value in delivery["command_types"].items():
        lines.append(f"  {pascal(name)} = {value},")
    lines.extend(["};", "", "enum class ApplicationResult : uint8_t {"])
    for name, value in delivery["results"].items():
        lines.append(f"  {pascal(name)} = {value},")
    lines.extend(["};", "", "} // namespace ride_ble_protocol_generated", ""])
    return "\n".join(lines)


def update(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"generated BLE contract is stale: {path.relative_to(ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"generated {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    contract = load_contract()
    outputs = (
        (SWIFT_OUTPUT, render_swift(contract)),
        (CPP_OUTPUT, render_cpp(contract)),
        (ROOT / "ios-app/BikeComputer/WorkoutShared/RideAutomationSourceHealth.generated.swift",
         "// Generated by tools/generate_ride_ble_contract.py. Do not edit.\n"
         "nonisolated enum RideAutomationSourceHealth {\n"
         + "".join(f"    static let {camel(name)}: UInt16 = 1 << {bit}\n"
                   for name, bit in contract["automation_source_health"].items())
         + f"    static let mask: UInt16 = {sum(1 << bit for bit in contract['automation_source_health'].values())}\n"
         + "}\n"),
    )
    results = [update(path, content, args.check) for path, content in outputs]
    return 0 if all(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
