import Foundation

/// Generated by the actual ESP32/LVGL renderer. The app only composes sample
/// tiles at their native pixel bounds; it does not approximate device fonts,
/// duplicate the round safe-area formula, or fit a square grid into a circle.
nonisolated struct RideStatsPreviewSpec: Decodable {
    struct Tile: Decodable {
        let sprite: String?
        let bounds: [Int]
        let fonts: [Int]
    }

    struct Board: Decodable {
        let width: Int
        let height: Int
        let round: Bool
        let normal: [String: Tile]
        let pairs: [String: Tile]

        func tiles(for widgets: [UInt8]) -> [Tile] {
            guard widgets.count == 7 else { return [] }
            var result: [Tile] = []
            if let hero = normal["0:\(widgets[0])"] { result.append(hero) }
            for row in 0..<3 {
                let left = row * 2 + 1
                let right = left + 1
                if let paired = pairs["\(row):\(widgets[left]):\(widgets[right])"] {
                    result.append(paired)
                } else {
                    if let tile = normal["\(left):\(widgets[left])"] { result.append(tile) }
                    if let tile = normal["\(right):\(widgets[right])"] { result.append(tile) }
                }
            }
            return result
        }
    }

    let schema: Int
    let boards: [String: Board]
    let sprites: [String: [Int]]

    func board(firmwareTarget: String, widgets: [UInt8]) -> Board? {
        guard schema == 1 else { return nil }
        // Firmware update metadata identifies the board independently of BLE
        // screen capabilities. Before metadata arrives, show the 1.75" example.
        let target = firmwareTarget == "WAVESHARE_AMOLED_206"
            ? firmwareTarget : "WAVESHARE_AMOLED_175"
        // Keep the whole example coherent: choosing a sensor widget enables
        // that sensor's sample data in all Smart fields, not only its own row.
        let selected = widgets.compactMap(RideBLERideStatsWidgetV1.init(rawValue:))
        let hasPower = selected.contains {
            switch $0 {
            case .power, .powerZone, .powerZoneTime, .powerZoneRange: return true
            default: return false
            }
        }
        let sensors = (hasPower ? 1 : 0) | (selected.contains(.cadence) ? 2 : 0)
        return boards["\(target):\(sensors)"]
    }
}
