/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CatalogBindings src/worker-configuration.generated.d.ts` (hash: db03cb232dbb5beabe7179930567094c)
interface __BaseEnv_CatalogBindings {
	DB: D1Database;
	LIBRARY_BOOTSTRAP_CLIENT_RATE_LIMITER: RateLimit;
	LIBRARY_BOOTSTRAP_GLOBAL_RATE_LIMITER: RateLimit;
	SHARE_CREATE_RATE_LIMITER: RateLimit;
	SHARE_PREVIEW_RATE_LIMITER: RateLimit;
	SHARE_LANDING_RATE_LIMITER: RateLimit;
	SHARE_CLAIM_RATE_LIMITER: RateLimit;
	LINK_CODE_CREATE_RATE_LIMITER: RateLimit;
	LINK_CODE_CLAIM_RATE_LIMITER: RateLimit;
	PROMOTION_RATE_LIMITER: RateLimit;
	PUBLIC_MUTATION_GLOBAL_RATE_LIMITER: RateLimit;
	LIBRARY_MUTATION_RATE_LIMITER: RateLimit;
	SERVICE_MUTATION_RATE_LIMITER: RateLimit;
	MAP_DELIVERY_ENABLED: string;
	ENVIRONMENT: string;
	PUBLIC_BASE_URL: string;
	R2_ACCOUNT_ID: string;
	R2_DEVELOPMENT_BUCKET: string;
	R2_PRODUCTION_BUCKET: string;
	R2_OBJECT_PREFIX: string;
	RETENTION_GRACE_DAYS: string;
	APPLE_TEAM_ID: string;
	PRODUCTION_BUNDLE_ID: string;
	DEVELOPMENT_BUNDLE_ID: string;
	APP_STORE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		DB: D1Database;
		LIBRARY_BOOTSTRAP_CLIENT_RATE_LIMITER: RateLimit;
		LIBRARY_BOOTSTRAP_GLOBAL_RATE_LIMITER: RateLimit;
		SHARE_CREATE_RATE_LIMITER: RateLimit;
		SHARE_PREVIEW_RATE_LIMITER: RateLimit;
		SHARE_LANDING_RATE_LIMITER: RateLimit;
		SHARE_CLAIM_RATE_LIMITER: RateLimit;
		LINK_CODE_CREATE_RATE_LIMITER: RateLimit;
		LINK_CODE_CLAIM_RATE_LIMITER: RateLimit;
		PROMOTION_RATE_LIMITER: RateLimit;
		PUBLIC_MUTATION_GLOBAL_RATE_LIMITER: RateLimit;
		LIBRARY_MUTATION_RATE_LIMITER: RateLimit;
		SERVICE_MUTATION_RATE_LIMITER: RateLimit;
		MAP_DELIVERY_ENABLED: string;
		ENVIRONMENT: string;
		PUBLIC_BASE_URL: string;
		R2_ACCOUNT_ID: string;
		R2_DEVELOPMENT_BUCKET: string;
		R2_PRODUCTION_BUCKET: string;
		R2_OBJECT_PREFIX: string;
		RETENTION_GRACE_DAYS: string;
		APPLE_TEAM_ID: string;
		PRODUCTION_BUNDLE_ID: string;
		DEVELOPMENT_BUNDLE_ID: string;
		APP_STORE_URL: string;
	}
	interface Env extends __BaseEnv_CatalogBindings {}
}
interface CatalogBindings extends __BaseEnv_CatalogBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MAP_DELIVERY_ENABLED" | "ENVIRONMENT" | "PUBLIC_BASE_URL" | "R2_ACCOUNT_ID" | "R2_DEVELOPMENT_BUCKET" | "R2_PRODUCTION_BUCKET" | "R2_OBJECT_PREFIX" | "RETENTION_GRACE_DAYS" | "APPLE_TEAM_ID" | "PRODUCTION_BUNDLE_ID" | "DEVELOPMENT_BUNDLE_ID" | "APP_STORE_URL">> {}
}
